// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 F4 contributors

import Foundation

struct DictationStrings {
    let pageTitle: String
    let hubDescription: String
    let enableToggle: String
    let settingsCaption: String
    let fnHint: String
    let privacyNote: String

    let engineHeading: String
    /// %@ is the model file name.
    let engineReady: String
    /// %@ is the server address.
    let engineExternal: String
    let engineStopped: String
    let engineStarting: String
    let engineMissingBinary: String
    /// %@ is the model path.
    let engineMissingModel: String
    let engineFailed: String
    let modelLabel: String
    let chooseModel: String
    let downloadModel: String
    let endpointLabel: String
    let check: String

    let languageLabel: String
    let languageSystem: String
    let languageAuto: String
    let polishLabel: String
    let polishOff: String
    let polishSmart: String
    let polishAlways: String
    let polishCaption: String
    let vocabularyLabel: String
    let vocabularyPlaceholder: String
    let vocabularyCaption: String
    let lastDictation: String
    let copy: String

    let statusListening: String
    let statusHandsFree: String
    let statusTranscribing: String
    let statusPolishing: String
    let statusPasted: String
    let statusCopied: String
    let statusNotPasted: String
    let noteSecureInput: String
    let noteNoAccessibility: String

    let errorMicrophoneDenied: String
    let errorMicrophoneUnavailable: String
    let errorEndpointInvalid: String
    let errorTranscriptionFailed: String
    let errorNoSpeech: String

    let historySearch: String
    let historyEmpty: String
    let historyNoResults: String
    let historyDelete: String
}

extension FeatureStrings {
    static func dictation(_ language: AppLanguage) -> DictationStrings {
        switch language {
        case .enUS: return DictationStrings(
            pageTitle: "Dictation",
            hubDescription: "Hold a shortcut, speak, and the text is typed wherever the cursor is. Transcribed on this Mac with whisper.cpp.",
            enableToggle: "Dictate with a shortcut",
            settingsCaption: "Hold Fn while you speak and let go to insert the text; press Fn twice to keep listening hands-free until you press it again. The shortcut below works the same way. Esc cancels.",
            fnHint: "For Fn to reach dictation, set System Settings › Keyboard › “Press 🌐 key to” to “Do Nothing”.",
            privacyNote: "Audio and text never leave this Mac: whisper.cpp transcribes on this machine and the cleanup uses the same local model as Clipboard AI.",
            engineHeading: "Transcription engine",
            engineReady: "Ready, using %@",
            engineExternal: "Using the server already running at %@",
            engineStopped: "Starts with the first dictation and stops after a while unused.",
            engineStarting: "Loading the model",
            engineMissingBinary: "whisper.cpp is not installed. Run “brew install whisper-cpp” in Terminal.",
            engineMissingModel: "There is no model file at %@. Download one or choose another file.",
            engineFailed: "The transcription engine could not start.",
            modelLabel: "Model file",
            chooseModel: "Choose…",
            downloadModel: "Download models",
            endpointLabel: "Server",
            check: "Check",
            languageLabel: "Spoken language",
            languageSystem: "Same as this Mac",
            languageAuto: "Detect automatically",
            polishLabel: "AI cleanup",
            polishOff: "Off",
            polishSmart: "When it helps",
            polishAlways: "Always",
            polishCaption: "Removes hesitations and false starts, keeps only your final correction and lays out lists. “When it helps” skips the model for clean sentences, so they paste at once.",
            vocabularyLabel: "Vocabulary",
            vocabularyPlaceholder: "Names, products, jargon, separated by commas",
            vocabularyCaption: "Spelled exactly as written here, in the transcription and in the cleanup.",
            lastDictation: "Last dictation",
            copy: "Copy",
            statusListening: "Listening",
            statusHandsFree: "Hands-free",
            statusTranscribing: "Transcribing",
            statusPolishing: "Polishing",
            statusPasted: "Pasted",
            statusCopied: "Copied",
            statusNotPasted: "Not pasted anywhere",
            noteSecureInput: "A password field is active, so the text was copied instead of pasted.",
            noteNoAccessibility: "Copied. Allow Accessibility so dictation can paste by itself.",
            errorMicrophoneDenied: "Microphone access is off. Allow it in System Settings › Privacy & Security › Microphone.",
            errorMicrophoneUnavailable: "The microphone could not be started.",
            errorEndpointInvalid: "The server address must be on this Mac.",
            errorTranscriptionFailed: "The transcription failed.",
            errorNoSpeech: "No speech was heard.",
            historySearch: "Search dictations",
            historyEmpty: "No dictations yet.",
            historyNoResults: "No dictations match.",
            historyDelete: "Delete")
        case .ptBR: return DictationStrings(
            pageTitle: "Ditado",
            hubDescription: "Segure um atalho, fale, e o texto é digitado onde estiver o cursor. Transcrito neste Mac com o whisper.cpp.",
            enableToggle: "Ditar com um atalho",
            settingsCaption: "Segure Fn enquanto fala e solte para inserir o texto; aperte Fn duas vezes para continuar sem as mãos até apertar de novo. O atalho abaixo funciona igual. Esc cancela.",
            fnHint: "Para Fn chegar ao ditado, em Ajustes do Sistema › Teclado defina “Pressionar a tecla 🌐 para” como “Não Fazer Nada”.",
            privacyNote: "O áudio e o texto nunca saem deste Mac: o whisper.cpp transcreve nesta máquina e a limpeza usa o mesmo modelo local da IA do clipboard.",
            engineHeading: "Motor de transcrição",
            engineReady: "Pronto, usando %@",
            engineExternal: "Usando o servidor que já está rodando em %@",
            engineStopped: "Inicia no primeiro ditado e para depois de um tempo sem uso.",
            engineStarting: "Carregando o modelo",
            engineMissingBinary: "O whisper.cpp não está instalado. Rode “brew install whisper-cpp” no Terminal.",
            engineMissingModel: "Não há nenhum modelo em %@. Baixe um ou escolha outro arquivo.",
            engineFailed: "O motor de transcrição não conseguiu iniciar.",
            modelLabel: "Arquivo do modelo",
            chooseModel: "Escolher…",
            downloadModel: "Baixar modelos",
            endpointLabel: "Servidor",
            check: "Verificar",
            languageLabel: "Idioma falado",
            languageSystem: "O mesmo deste Mac",
            languageAuto: "Detectar automaticamente",
            polishLabel: "Limpeza com IA",
            polishOff: "Desligada",
            polishSmart: "Quando ajudar",
            polishAlways: "Sempre",
            polishCaption: "Tira hesitações e começos falsos, fica só com a sua última correção e organiza listas. “Quando ajudar” pula o modelo em frases limpas, que são coladas na hora.",
            vocabularyLabel: "Vocabulário",
            vocabularyPlaceholder: "Nomes, produtos, jargões, separados por vírgulas",
            vocabularyCaption: "Escritos exatamente como aqui, na transcrição e na limpeza.",
            lastDictation: "Último ditado",
            copy: "Copiar",
            statusListening: "Ouvindo",
            statusHandsFree: "Sem as mãos",
            statusTranscribing: "Transcrevendo",
            statusPolishing: "Refinando",
            statusPasted: "Colado",
            statusCopied: "Copiado",
            statusNotPasted: "Não foi colado em lugar nenhum",
            noteSecureInput: "Um campo de senha está ativo, então o texto foi copiado em vez de colado.",
            noteNoAccessibility: "Copiado. Permita a Acessibilidade para o ditado colar sozinho.",
            errorMicrophoneDenied: "O acesso ao microfone está desligado. Permita em Ajustes do Sistema › Privacidade e Segurança › Microfone.",
            errorMicrophoneUnavailable: "Não foi possível iniciar o microfone.",
            errorEndpointInvalid: "O endereço do servidor precisa estar neste Mac.",
            errorTranscriptionFailed: "A transcrição falhou.",
            errorNoSpeech: "Nenhuma fala foi ouvida.",
            historySearch: "Buscar ditados",
            historyEmpty: "Nenhum ditado ainda.",
            historyNoResults: "Nenhum ditado corresponde.",
            historyDelete: "Apagar")
        case .tr: return DictationStrings(
            pageTitle: "Dikte",
            hubDescription: "Bir kısayolu basılı tut, konuş; metin imlecin olduğu yere yazılsın. whisper.cpp ile bu Mac’te yazıya dökülür.",
            enableToggle: "Kısayolla dikte et",
            settingsCaption: "Konuşurken Fn’yi basılı tut, metni eklemek için bırak; tekrar basana kadar eller serbest dinlemek için Fn’ye iki kez bas. Aşağıdaki kısayol da aynı şekilde çalışır. Esc iptal eder.",
            fnHint: "Fn’nin dikteye ulaşması için Sistem Ayarları › Klavye’de “🌐 tuşuna basınca” seçeneğini “Hiçbir Şey Yapma” yap.",
            privacyNote: "Ses ve metin bu Mac’ten asla çıkmaz: whisper.cpp bu makinede yazıya döker, temizleme de Pano yapay zekâsı ile aynı yerel modeli kullanır.",
            engineHeading: "Yazıya dökme motoru",
            engineReady: "Hazır, %@ kullanılıyor",
            engineExternal: "%@ adresinde zaten çalışan sunucu kullanılıyor",
            engineStopped: "İlk diktede başlar, bir süre kullanılmayınca durur.",
            engineStarting: "Model yükleniyor",
            engineMissingBinary: "whisper.cpp yüklü değil. Terminal’de “brew install whisper-cpp” komutunu çalıştır.",
            engineMissingModel: "%@ konumunda model dosyası yok. Bir tane indir ya da başka bir dosya seç.",
            engineFailed: "Yazıya dökme motoru başlatılamadı.",
            modelLabel: "Model dosyası",
            chooseModel: "Seç…",
            downloadModel: "Model indir",
            endpointLabel: "Sunucu",
            check: "Denetle",
            languageLabel: "Konuşulan dil",
            languageSystem: "Bu Mac’in dili",
            languageAuto: "Otomatik algıla",
            polishLabel: "Yapay zekâ ile temizleme",
            polishOff: "Kapalı",
            polishSmart: "Yararlı olduğunda",
            polishAlways: "Her zaman",
            polishCaption: "Duraksamaları ve yanlış başlangıçları siler, yalnızca son düzeltmeni tutar ve listeleri düzenler. “Yararlı olduğunda” temiz cümlelerde modeli atlar, böylece hemen yapıştırılır.",
            vocabularyLabel: "Sözcük listesi",
            vocabularyPlaceholder: "Adlar, ürünler, terimler; virgülle ayrılmış",
            vocabularyCaption: "Hem yazıya dökmede hem temizlemede tam buradaki gibi yazılır.",
            lastDictation: "Son dikte",
            copy: "Kopyala",
            statusListening: "Dinliyor",
            statusHandsFree: "Eller serbest",
            statusTranscribing: "Yazıya dökülüyor",
            statusPolishing: "Düzenleniyor",
            statusPasted: "Yapıştırıldı",
            statusCopied: "Kopyalandı",
            statusNotPasted: "Hiçbir yere yapıştırılmadı",
            noteSecureInput: "Bir parola alanı etkin, bu yüzden metin yapıştırılmak yerine kopyalandı.",
            noteNoAccessibility: "Kopyalandı. Diktenin kendi kendine yapıştırabilmesi için Erişilebilirlik izni ver.",
            errorMicrophoneDenied: "Mikrofon erişimi kapalı. Sistem Ayarları › Gizlilik ve Güvenlik › Mikrofon bölümünden izin ver.",
            errorMicrophoneUnavailable: "Mikrofon başlatılamadı.",
            errorEndpointInvalid: "Sunucu adresi bu Mac’te olmalı.",
            errorTranscriptionFailed: "Yazıya dökme başarısız oldu.",
            errorNoSpeech: "Hiç konuşma duyulmadı.",
            historySearch: "Diktelerde ara",
            historyEmpty: "Henüz dikte yok.",
            historyNoResults: "Eşleşen dikte yok.",
            historyDelete: "Sil")
        case .ru: return DictationStrings(
            pageTitle: "Диктовка",
            hubDescription: "Удерживайте сочетание клавиш, говорите, и текст появится там, где стоит курсор. Распознаётся на этом Mac с помощью whisper.cpp.",
            enableToggle: "Диктовать по сочетанию клавиш",
            settingsCaption: "Удерживайте Fn, пока говорите, и отпустите, чтобы вставить текст; нажмите Fn дважды, чтобы слушать без рук до следующего нажатия. Сочетание ниже работает так же. Esc отменяет.",
            fnHint: "Чтобы Fn работала для диктовки, в Системных настройках › Клавиатура выберите для «Нажатие клавиши 🌐» вариант «Ничего не делать».",
            privacyNote: "Звук и текст никогда не покидают этот Mac: whisper.cpp распознаёт речь на этом компьютере, а очистка использует ту же локальную модель, что и «ИИ в буфере обмена».",
            engineHeading: "Движок распознавания",
            engineReady: "Готово, используется %@",
            engineExternal: "Используется уже запущенный сервер %@",
            engineStopped: "Запускается при первой диктовке и останавливается, если долго не используется.",
            engineStarting: "Загрузка модели",
            engineMissingBinary: "whisper.cpp не установлен. Выполните «brew install whisper-cpp» в Терминале.",
            engineMissingModel: "По пути %@ нет файла модели. Скачайте модель или выберите другой файл.",
            engineFailed: "Не удалось запустить движок распознавания.",
            modelLabel: "Файл модели",
            chooseModel: "Выбрать…",
            downloadModel: "Скачать модели",
            endpointLabel: "Сервер",
            check: "Проверить",
            languageLabel: "Язык речи",
            languageSystem: "Как на этом Mac",
            languageAuto: "Определять автоматически",
            polishLabel: "Очистка ИИ",
            polishOff: "Выкл.",
            polishSmart: "Когда полезно",
            polishAlways: "Всегда",
            polishCaption: "Убирает запинки и оговорки, оставляет только последнее исправление и оформляет списки. «Когда полезно» пропускает модель для чистых фраз, и они вставляются сразу.",
            vocabularyLabel: "Словарь",
            vocabularyPlaceholder: "Имена, продукты, термины через запятую",
            vocabularyCaption: "Пишутся точно так, как здесь, и при распознавании, и при очистке.",
            lastDictation: "Последняя диктовка",
            copy: "Скопировать",
            statusListening: "Слушаю",
            statusHandsFree: "Без рук",
            statusTranscribing: "Распознаю",
            statusPolishing: "Очищаю",
            statusPasted: "Вставлено",
            statusCopied: "Скопировано",
            statusNotPasted: "Никуда не вставлено",
            noteSecureInput: "Активно поле пароля, поэтому текст скопирован, а не вставлен.",
            noteNoAccessibility: "Скопировано. Разрешите Универсальный доступ, чтобы диктовка вставляла текст сама.",
            errorMicrophoneDenied: "Доступ к микрофону выключен. Разрешите его в Системных настройках › Конфиденциальность и безопасность › Микрофон.",
            errorMicrophoneUnavailable: "Не удалось включить микрофон.",
            errorEndpointInvalid: "Адрес сервера должен быть на этом Mac.",
            errorTranscriptionFailed: "Не удалось распознать речь.",
            errorNoSpeech: "Речь не услышана.",
            historySearch: "Искать в диктовках",
            historyEmpty: "Диктовок пока нет.",
            historyNoResults: "Подходящих диктовок нет.",
            historyDelete: "Удалить")
        case .es: return DictationStrings(
            pageTitle: "Dictado",
            hubDescription: "Mantén pulsado un atajo, habla y el texto se escribe donde esté el cursor. Se transcribe en este Mac con whisper.cpp.",
            enableToggle: "Dictar con un atajo",
            settingsCaption: "Mantén pulsada Fn mientras hablas y suéltala para insertar el texto; pulsa Fn dos veces para seguir en manos libres hasta que la vuelvas a pulsar. El atajo de abajo funciona igual. Esc cancela.",
            fnHint: "Para que Fn llegue al dictado, en Ajustes del Sistema › Teclado pon «Pulsar la tecla 🌐 para» en «No hacer nada».",
            privacyNote: "El audio y el texto nunca salen de este Mac: whisper.cpp transcribe en esta máquina y la limpieza usa el mismo modelo local que la IA del portapapeles.",
            engineHeading: "Motor de transcripción",
            engineReady: "Listo, con %@",
            engineExternal: "Usando el servidor que ya está en marcha en %@",
            engineStopped: "Arranca con el primer dictado y se detiene tras un rato sin usarse.",
            engineStarting: "Cargando el modelo",
            engineMissingBinary: "whisper.cpp no está instalado. Ejecuta “brew install whisper-cpp” en Terminal.",
            engineMissingModel: "No hay ningún modelo en %@. Descarga uno o elige otro archivo.",
            engineFailed: "El motor de transcripción no ha podido arrancar.",
            modelLabel: "Archivo del modelo",
            chooseModel: "Elegir…",
            downloadModel: "Descargar modelos",
            endpointLabel: "Servidor",
            check: "Comprobar",
            languageLabel: "Idioma hablado",
            languageSystem: "El de este Mac",
            languageAuto: "Detectar automáticamente",
            polishLabel: "Limpieza con IA",
            polishOff: "Desactivada",
            polishSmart: "Cuando ayude",
            polishAlways: "Siempre",
            polishCaption: "Quita titubeos y arranques en falso, se queda solo con tu última corrección y ordena las listas. «Cuando ayude» no usa el modelo con frases limpias, que se pegan al momento.",
            vocabularyLabel: "Vocabulario",
            vocabularyPlaceholder: "Nombres, productos, jerga, separados por comas",
            vocabularyCaption: "Se escriben tal cual aparecen aquí, en la transcripción y en la limpieza.",
            lastDictation: "Último dictado",
            copy: "Copiar",
            statusListening: "Escuchando",
            statusHandsFree: "Manos libres",
            statusTranscribing: "Transcribiendo",
            statusPolishing: "Puliendo",
            statusPasted: "Pegado",
            statusCopied: "Copiado",
            statusNotPasted: "No se pegó en ningún sitio",
            noteSecureInput: "Hay un campo de contraseña activo, así que el texto se ha copiado en vez de pegarse.",
            noteNoAccessibility: "Copiado. Da acceso de Accesibilidad para que el dictado pueda pegar por sí solo.",
            errorMicrophoneDenied: "El acceso al micrófono está desactivado. Actívalo en Ajustes del Sistema › Privacidad y seguridad › Micrófono.",
            errorMicrophoneUnavailable: "No se ha podido iniciar el micrófono.",
            errorEndpointInvalid: "La dirección del servidor tiene que estar en este Mac.",
            errorTranscriptionFailed: "La transcripción ha fallado.",
            errorNoSpeech: "No se ha oído ninguna voz.",
            historySearch: "Buscar dictados",
            historyEmpty: "Todavía no hay dictados.",
            historyNoResults: "Ningún dictado coincide.",
            historyDelete: "Eliminar")
        case .de: return DictationStrings(
            pageTitle: "Diktat",
            hubDescription: "Kurzbefehl gedrückt halten, sprechen, und der Text erscheint dort, wo der Cursor steht. Transkribiert auf diesem Mac mit whisper.cpp.",
            enableToggle: "Mit Kurzbefehl diktieren",
            settingsCaption: "Halte Fn beim Sprechen gedrückt und lass los, um den Text einzufügen; drücke Fn zweimal, um freihändig weiter zuzuhören, bis du sie erneut drückst. Der Kurzbefehl unten funktioniert genauso. Esc bricht ab.",
            fnHint: "Damit Fn beim Diktat ankommt, stelle in Systemeinstellungen › Tastatur „Taste 🌐 drücken, um“ auf „Keine Aktion“.",
            privacyNote: "Audio und Text verlassen diesen Mac nie: whisper.cpp transkribiert auf diesem Gerät, und die Bereinigung nutzt dasselbe lokale Modell wie die KI für die Zwischenablage.",
            engineHeading: "Transkriptions-Engine",
            engineReady: "Bereit, mit %@",
            engineExternal: "Nutzt den bereits laufenden Server unter %@",
            engineStopped: "Startet mit dem ersten Diktat und stoppt nach einer Weile ohne Nutzung.",
            engineStarting: "Modell wird geladen",
            engineMissingBinary: "whisper.cpp ist nicht installiert. Führe „brew install whisper-cpp“ im Terminal aus.",
            engineMissingModel: "Unter %@ liegt keine Modelldatei. Lade eine herunter oder wähle eine andere Datei.",
            engineFailed: "Die Transkriptions-Engine konnte nicht starten.",
            modelLabel: "Modelldatei",
            chooseModel: "Auswählen …",
            downloadModel: "Modelle laden",
            endpointLabel: "Server",
            check: "Prüfen",
            languageLabel: "Gesprochene Sprache",
            languageSystem: "Wie dieser Mac",
            languageAuto: "Automatisch erkennen",
            polishLabel: "KI-Bereinigung",
            polishOff: "Aus",
            polishSmart: "Wenn es hilft",
            polishAlways: "Immer",
            polishCaption: "Entfernt Zögern und Fehlstarts, behält nur deine letzte Korrektur und setzt Listen. „Wenn es hilft“ überspringt das Modell bei sauberen Sätzen, die sofort eingefügt werden.",
            vocabularyLabel: "Vokabular",
            vocabularyPlaceholder: "Namen, Produkte, Fachbegriffe, durch Kommas getrennt",
            vocabularyCaption: "Wird genau so geschrieben wie hier, in der Transkription und in der Bereinigung.",
            lastDictation: "Letztes Diktat",
            copy: "Kopieren",
            statusListening: "Hört zu",
            statusHandsFree: "Freihändig",
            statusTranscribing: "Transkribiert",
            statusPolishing: "Bereinigt",
            statusPasted: "Eingefügt",
            statusCopied: "Kopiert",
            statusNotPasted: "Nirgends eingefügt",
            noteSecureInput: "Ein Passwortfeld ist aktiv, daher wurde der Text kopiert statt eingefügt.",
            noteNoAccessibility: "Kopiert. Erlaube Bedienungshilfen, damit das Diktat selbst einfügen kann.",
            errorMicrophoneDenied: "Der Mikrofonzugriff ist aus. Erlaube ihn in Systemeinstellungen › Datenschutz & Sicherheit › Mikrofon.",
            errorMicrophoneUnavailable: "Das Mikrofon konnte nicht gestartet werden.",
            errorEndpointInvalid: "Die Serveradresse muss auf diesem Mac liegen.",
            errorTranscriptionFailed: "Die Transkription ist fehlgeschlagen.",
            errorNoSpeech: "Es war keine Sprache zu hören.",
            historySearch: "Diktate durchsuchen",
            historyEmpty: "Noch keine Diktate.",
            historyNoResults: "Kein Diktat passt.",
            historyDelete: "Löschen")
        case .fr: return DictationStrings(
            pageTitle: "Dictée",
            hubDescription: "Maintenez un raccourci, parlez, et le texte s’écrit là où se trouve le curseur. Transcrit sur ce Mac avec whisper.cpp.",
            enableToggle: "Dicter avec un raccourci",
            settingsCaption: "Maintenez Fn pendant que vous parlez et relâchez pour insérer le texte ; appuyez deux fois sur Fn pour écouter mains libres jusqu’au prochain appui. Le raccourci ci-dessous fonctionne pareil. Échap annule.",
            fnHint: "Pour que Fn serve à la dictée, réglez Réglages Système › Clavier › « Appuyer sur la touche 🌐 pour » sur « Ne rien faire ».",
            privacyNote: "L’audio et le texte ne quittent jamais ce Mac : whisper.cpp transcrit sur cette machine et le nettoyage utilise le même modèle local que l’IA du presse-papiers.",
            engineHeading: "Moteur de transcription",
            engineReady: "Prêt, avec %@",
            engineExternal: "Utilise le serveur déjà lancé sur %@",
            engineStopped: "Démarre à la première dictée et s’arrête après un moment sans usage.",
            engineStarting: "Chargement du modèle",
            engineMissingBinary: "whisper.cpp n’est pas installé. Lancez « brew install whisper-cpp » dans le Terminal.",
            engineMissingModel: "Aucun fichier de modèle dans %@. Téléchargez-en un ou choisissez un autre fichier.",
            engineFailed: "Le moteur de transcription n’a pas pu démarrer.",
            modelLabel: "Fichier du modèle",
            chooseModel: "Choisir…",
            downloadModel: "Télécharger des modèles",
            endpointLabel: "Serveur",
            check: "Vérifier",
            languageLabel: "Langue parlée",
            languageSystem: "Celle de ce Mac",
            languageAuto: "Détection automatique",
            polishLabel: "Nettoyage par IA",
            polishOff: "Désactivé",
            polishSmart: "Quand c’est utile",
            polishAlways: "Toujours",
            polishCaption: "Retire les hésitations et les faux départs, ne garde que votre dernière correction et met les listes en forme. « Quand c’est utile » saute le modèle pour les phrases propres, collées aussitôt.",
            vocabularyLabel: "Vocabulaire",
            vocabularyPlaceholder: "Noms, produits, jargon, séparés par des virgules",
            vocabularyCaption: "Écrits exactement comme ici, dans la transcription et le nettoyage.",
            lastDictation: "Dernière dictée",
            copy: "Copier",
            statusListening: "À l’écoute",
            statusHandsFree: "Mains libres",
            statusTranscribing: "Transcription",
            statusPolishing: "Nettoyage",
            statusPasted: "Collé",
            statusCopied: "Copié",
            statusNotPasted: "Collé nulle part",
            noteSecureInput: "Un champ de mot de passe est actif, le texte a donc été copié au lieu d’être collé.",
            noteNoAccessibility: "Copié. Autorisez l’Accessibilité pour que la dictée colle toute seule.",
            errorMicrophoneDenied: "L’accès au micro est désactivé. Autorisez-le dans Réglages Système › Confidentialité et sécurité › Micro.",
            errorMicrophoneUnavailable: "Le micro n’a pas pu démarrer.",
            errorEndpointInvalid: "L’adresse du serveur doit être sur ce Mac.",
            errorTranscriptionFailed: "La transcription a échoué.",
            errorNoSpeech: "Aucune voix n’a été entendue.",
            historySearch: "Rechercher dans les dictées",
            historyEmpty: "Aucune dictée pour l’instant.",
            historyNoResults: "Aucune dictée ne correspond.",
            historyDelete: "Supprimer")
        case .it: return DictationStrings(
            pageTitle: "Dettatura",
            hubDescription: "Tieni premuta un’abbreviazione, parla, e il testo viene scritto dove si trova il cursore. Trascritto su questo Mac con whisper.cpp.",
            enableToggle: "Detta con un’abbreviazione",
            settingsCaption: "Tieni premuto Fn mentre parli e rilascialo per inserire il testo; premi Fn due volte per ascoltare a mani libere finché non lo premi di nuovo. L’abbreviazione qui sotto funziona allo stesso modo. Esc annulla.",
            fnHint: "Perché Fn arrivi alla dettatura, in Impostazioni di Sistema › Tastiera imposta “Premi il tasto 🌐 per” su “Non fare nulla”.",
            privacyNote: "Audio e testo non lasciano mai questo Mac: whisper.cpp trascrive su questa macchina e la pulizia usa lo stesso modello locale dell’IA degli appunti.",
            engineHeading: "Motore di trascrizione",
            engineReady: "Pronto, con %@",
            engineExternal: "Usa il server già in esecuzione su %@",
            engineStopped: "Si avvia con la prima dettatura e si ferma dopo un po’ di inattività.",
            engineStarting: "Caricamento del modello",
            engineMissingBinary: "whisper.cpp non è installato. Esegui “brew install whisper-cpp” nel Terminale.",
            engineMissingModel: "Nessun file di modello in %@. Scaricane uno o scegli un altro file.",
            engineFailed: "Il motore di trascrizione non è riuscito ad avviarsi.",
            modelLabel: "File del modello",
            chooseModel: "Scegli…",
            downloadModel: "Scarica modelli",
            endpointLabel: "Server",
            check: "Verifica",
            languageLabel: "Lingua parlata",
            languageSystem: "Quella di questo Mac",
            languageAuto: "Rileva automaticamente",
            polishLabel: "Pulizia con IA",
            polishOff: "Disattivata",
            polishSmart: "Quando serve",
            polishAlways: "Sempre",
            polishCaption: "Toglie esitazioni e false partenze, tiene solo la tua ultima correzione e impagina gli elenchi. “Quando serve” salta il modello per le frasi pulite, che vengono incollate subito.",
            vocabularyLabel: "Vocabolario",
            vocabularyPlaceholder: "Nomi, prodotti, gergo, separati da virgole",
            vocabularyCaption: "Scritti esattamente come qui, nella trascrizione e nella pulizia.",
            lastDictation: "Ultima dettatura",
            copy: "Copia",
            statusListening: "In ascolto",
            statusHandsFree: "Mani libere",
            statusTranscribing: "Trascrizione",
            statusPolishing: "Rifinitura",
            statusPasted: "Incollato",
            statusCopied: "Copiato",
            statusNotPasted: "Non incollato da nessuna parte",
            noteSecureInput: "È attivo un campo password, quindi il testo è stato copiato invece che incollato.",
            noteNoAccessibility: "Copiato. Consenti l’Accessibilità perché la dettatura possa incollare da sola.",
            errorMicrophoneDenied: "L’accesso al microfono è disattivato. Consentilo in Impostazioni di Sistema › Privacy e sicurezza › Microfono.",
            errorMicrophoneUnavailable: "Impossibile avviare il microfono.",
            errorEndpointInvalid: "L’indirizzo del server deve essere su questo Mac.",
            errorTranscriptionFailed: "La trascrizione non è riuscita.",
            errorNoSpeech: "Non è stata sentita nessuna voce.",
            historySearch: "Cerca nelle dettature",
            historyEmpty: "Ancora nessuna dettatura.",
            historyNoResults: "Nessuna dettatura corrisponde.",
            historyDelete: "Elimina")
        case .ja: return DictationStrings(
            pageTitle: "音声入力",
            hubDescription: "ショートカットを押したまま話すと、カーソルの位置にテキストが入力されます。whisper.cppでこのMac上で文字起こしします。",
            enableToggle: "ショートカットで音声入力",
            settingsCaption: "話している間Fnを押し続け、離すとテキストが挿入されます。Fnを2回押すと、もう一度押すまでハンズフリーで聞き続けます。下のショートカットも同じように使えます。Escでキャンセルします。",
            fnHint: "Fnで音声入力を使うには、システム設定 › キーボードで「🌐キーを押して」を「何もしない」に設定してください。",
            privacyNote: "音声とテキストがこのMacの外に出ることはありません。whisper.cppがこのMac上で文字起こしし、整形にはクリップボード AIと同じローカルモデルを使います。",
            engineHeading: "文字起こしエンジン",
            engineReady: "準備完了（%@を使用）",
            engineExternal: "%@ で動作中のサーバを使用",
            engineStopped: "最初の音声入力で起動し、しばらく使わないと停止します。",
            engineStarting: "モデルを読み込み中",
            engineMissingBinary: "whisper.cppがインストールされていません。ターミナルで「brew install whisper-cpp」を実行してください。",
            engineMissingModel: "%@ にモデルファイルがありません。ダウンロードするか、別のファイルを選んでください。",
            engineFailed: "文字起こしエンジンを起動できませんでした。",
            modelLabel: "モデルファイル",
            chooseModel: "選択…",
            downloadModel: "モデルをダウンロード",
            endpointLabel: "サーバ",
            check: "確認",
            languageLabel: "話す言語",
            languageSystem: "このMacと同じ",
            languageAuto: "自動検出",
            polishLabel: "AIによる整形",
            polishOff: "オフ",
            polishSmart: "必要なときだけ",
            polishAlways: "常に",
            polishCaption: "言いよどみや言い直しを取り除き、最後の訂正だけを残し、箇条書きを整えます。「必要なときだけ」ではきれいな文はモデルを通さず、すぐに貼り付けます。",
            vocabularyLabel: "用語集",
            vocabularyPlaceholder: "名前、製品、専門用語をカンマ区切りで",
            vocabularyCaption: "文字起こしでも整形でも、ここに書いたとおりに表記します。",
            lastDictation: "最後の音声入力",
            copy: "コピー",
            statusListening: "聞き取り中",
            statusHandsFree: "ハンズフリー",
            statusTranscribing: "文字起こし中",
            statusPolishing: "整形中",
            statusPasted: "貼り付けました",
            statusCopied: "コピーしました",
            statusNotPasted: "どこにも貼り付けられませんでした",
            noteSecureInput: "パスワード欄が有効なため、テキストは貼り付けずにコピーしました。",
            noteNoAccessibility: "コピーしました。音声入力が自動で貼り付けられるよう、アクセシビリティを許可してください。",
            errorMicrophoneDenied: "マイクへのアクセスがオフです。システム設定 › プライバシーとセキュリティ › マイクで許可してください。",
            errorMicrophoneUnavailable: "マイクを開始できませんでした。",
            errorEndpointInvalid: "サーバのアドレスはこのMac上である必要があります。",
            errorTranscriptionFailed: "文字起こしに失敗しました。",
            errorNoSpeech: "音声が聞き取れませんでした。",
            historySearch: "音声入力を検索",
            historyEmpty: "音声入力の履歴はまだありません。",
            historyNoResults: "一致する音声入力はありません。",
            historyDelete: "削除")
        case .ko: return DictationStrings(
            pageTitle: "받아쓰기",
            hubDescription: "단축키를 누른 채 말하면 커서가 있는 곳에 텍스트가 입력됩니다. whisper.cpp로 이 Mac에서 받아씁니다.",
            enableToggle: "단축키로 받아쓰기",
            settingsCaption: "말하는 동안 Fn을 누르고 있다가 떼면 텍스트가 삽입됩니다. Fn을 두 번 누르면 다시 누를 때까지 핸즈프리로 계속 듣습니다. 아래 단축키도 똑같이 동작합니다. Esc를 누르면 취소됩니다.",
            fnHint: "Fn으로 받아쓰려면 시스템 설정 › 키보드에서 ‘🌐 키를 눌러’를 ‘아무것도 안 함’으로 설정하세요.",
            privacyNote: "오디오와 텍스트는 이 Mac을 떠나지 않습니다. whisper.cpp가 이 컴퓨터에서 받아쓰고, 정리는 클립보드 AI와 같은 로컬 모델을 사용합니다.",
            engineHeading: "받아쓰기 엔진",
            engineReady: "준비됨, %@ 사용 중",
            engineExternal: "%@에서 이미 실행 중인 서버 사용 중",
            engineStopped: "처음 받아쓸 때 시작되고, 한동안 사용하지 않으면 멈춥니다.",
            engineStarting: "모델 불러오는 중",
            engineMissingBinary: "whisper.cpp가 설치되어 있지 않습니다. 터미널에서 “brew install whisper-cpp”를 실행하세요.",
            engineMissingModel: "%@에 모델 파일이 없습니다. 모델을 다운로드하거나 다른 파일을 선택하세요.",
            engineFailed: "받아쓰기 엔진을 시작하지 못했습니다.",
            modelLabel: "모델 파일",
            chooseModel: "선택…",
            downloadModel: "모델 다운로드",
            endpointLabel: "서버",
            check: "확인",
            languageLabel: "말하는 언어",
            languageSystem: "이 Mac과 같게",
            languageAuto: "자동 감지",
            polishLabel: "AI 정리",
            polishOff: "끔",
            polishSmart: "도움이 될 때",
            polishAlways: "항상",
            polishCaption: "머뭇거림과 잘못 시작한 말을 지우고, 마지막 정정만 남기며, 목록을 정리합니다. “도움이 될 때”는 깔끔한 문장에서 모델을 건너뛰어 바로 붙여넣습니다.",
            vocabularyLabel: "어휘",
            vocabularyPlaceholder: "이름, 제품, 전문 용어를 쉼표로 구분",
            vocabularyCaption: "받아쓰기와 정리 모두에서 여기 적은 그대로 표기합니다.",
            lastDictation: "마지막 받아쓰기",
            copy: "복사",
            statusListening: "듣는 중",
            statusHandsFree: "핸즈프리",
            statusTranscribing: "받아쓰는 중",
            statusPolishing: "다듬는 중",
            statusPasted: "붙여넣음",
            statusCopied: "복사됨",
            statusNotPasted: "아무 곳에도 붙여넣지 않았습니다",
            noteSecureInput: "암호 입력란이 활성화되어 있어 텍스트를 붙여넣는 대신 복사했습니다.",
            noteNoAccessibility: "복사했습니다. 받아쓰기가 직접 붙여넣을 수 있도록 손쉬운 사용을 허용하세요.",
            errorMicrophoneDenied: "마이크 접근이 꺼져 있습니다. 시스템 설정 › 개인정보 보호 및 보안 › 마이크에서 허용하세요.",
            errorMicrophoneUnavailable: "마이크를 시작할 수 없습니다.",
            errorEndpointInvalid: "서버 주소는 이 Mac에 있어야 합니다.",
            errorTranscriptionFailed: "받아쓰기에 실패했습니다.",
            errorNoSpeech: "음성이 들리지 않았습니다.",
            historySearch: "받아쓰기 검색",
            historyEmpty: "아직 받아쓰기가 없습니다.",
            historyNoResults: "일치하는 받아쓰기가 없습니다.",
            historyDelete: "삭제")
        case .zhHans: return DictationStrings(
            pageTitle: "听写",
            hubDescription: "按住快捷键说话，文字就会输入到光标所在位置。使用 whisper.cpp 在这台 Mac 上转写。",
            enableToggle: "用快捷键听写",
            settingsCaption: "说话时按住 Fn，松开即插入文字；连按两次 Fn 则以免提方式持续聆听，直到再次按下。下方的快捷键用法相同。按 Esc 取消。",
            fnHint: "要让 Fn 用于听写，请在“系统设置” › “键盘”中将“按下 🌐 键时”设为“不执行任何操作”。",
            privacyNote: "音频和文字绝不会离开这台 Mac：whisper.cpp 在本机转写，整理使用与剪贴板 AI 相同的本地模型。",
            engineHeading: "转写引擎",
            engineReady: "就绪，正在使用 %@",
            engineExternal: "正在使用已在 %@ 运行的服务器",
            engineStopped: "首次听写时启动，闲置一段时间后停止。",
            engineStarting: "正在载入模型",
            engineMissingBinary: "未安装 whisper.cpp。请在“终端”中运行“brew install whisper-cpp”。",
            engineMissingModel: "%@ 处没有模型文件。请下载一个或选择其他文件。",
            engineFailed: "转写引擎无法启动。",
            modelLabel: "模型文件",
            chooseModel: "选择…",
            downloadModel: "下载模型",
            endpointLabel: "服务器",
            check: "检查",
            languageLabel: "说话语言",
            languageSystem: "与这台 Mac 相同",
            languageAuto: "自动检测",
            polishLabel: "AI 整理",
            polishOff: "关闭",
            polishSmart: "有帮助时",
            polishAlways: "始终",
            polishCaption: "去掉犹豫和说错的开头，只保留你最后的更正，并排好列表。“有帮助时”对干净的句子跳过模型，立即粘贴。",
            vocabularyLabel: "词汇表",
            vocabularyPlaceholder: "名字、产品、术语，用逗号分隔",
            vocabularyCaption: "在转写和整理中都严格按这里的写法输出。",
            lastDictation: "上次听写",
            copy: "拷贝",
            statusListening: "正在聆听",
            statusHandsFree: "免提",
            statusTranscribing: "正在转写",
            statusPolishing: "正在整理",
            statusPasted: "已粘贴",
            statusCopied: "已拷贝",
            statusNotPasted: "未粘贴到任何位置",
            noteSecureInput: "密码输入框处于活跃状态，因此文字已拷贝而非粘贴。",
            noteNoAccessibility: "已拷贝。允许“辅助功能”后，听写即可自动粘贴。",
            errorMicrophoneDenied: "麦克风访问已关闭。请在“系统设置” › “隐私与安全性” › “麦克风”中允许。",
            errorMicrophoneUnavailable: "无法启动麦克风。",
            errorEndpointInvalid: "服务器地址必须在这台 Mac 上。",
            errorTranscriptionFailed: "转写失败。",
            errorNoSpeech: "没有听到语音。",
            historySearch: "搜索听写",
            historyEmpty: "还没有听写记录。",
            historyNoResults: "没有匹配的听写。",
            historyDelete: "删除")
        case .zhTW: return DictationStrings(
            pageTitle: "聽寫",
            hubDescription: "按住快速鍵說話，文字就會輸入到游標所在位置。使用 whisper.cpp 在這台 Mac 上轉寫。",
            enableToggle: "用快速鍵聽寫",
            settingsCaption: "說話時按住 Fn，放開即插入文字；連按兩次 Fn 則以免持方式持續聆聽，直到再次按下。下方的快速鍵用法相同。按 Esc 取消。",
            fnHint: "若要讓 Fn 用於聽寫，請在「系統設定」›「鍵盤」中將「按下 🌐 鍵時」設為「不執行任何動作」。",
            privacyNote: "音訊與文字絕不會離開這台 Mac：whisper.cpp 在本機轉寫，整理使用與剪貼簿 AI 相同的本機模型。",
            engineHeading: "轉寫引擎",
            engineReady: "就緒，正在使用 %@",
            engineExternal: "正在使用已在 %@ 執行的伺服器",
            engineStopped: "第一次聽寫時啟動，閒置一段時間後停止。",
            engineStarting: "正在載入模型",
            engineMissingBinary: "尚未安裝 whisper.cpp。請在「終端機」執行「brew install whisper-cpp」。",
            engineMissingModel: "%@ 沒有模型檔案。請下載一個或選擇其他檔案。",
            engineFailed: "轉寫引擎無法啟動。",
            modelLabel: "模型檔案",
            chooseModel: "選擇…",
            downloadModel: "下載模型",
            endpointLabel: "伺服器",
            check: "檢查",
            languageLabel: "說話語言",
            languageSystem: "與這台 Mac 相同",
            languageAuto: "自動偵測",
            polishLabel: "AI 整理",
            polishOff: "關閉",
            polishSmart: "有幫助時",
            polishAlways: "永遠",
            polishCaption: "移除猶豫與說錯的開頭，只保留你最後的更正，並排好列表。「有幫助時」會對乾淨的句子略過模型，立即貼上。",
            vocabularyLabel: "詞彙表",
            vocabularyPlaceholder: "名稱、產品、術語，以逗號分隔",
            vocabularyCaption: "在轉寫與整理中都完全依照這裡的寫法。",
            lastDictation: "上次聽寫",
            copy: "拷貝",
            statusListening: "正在聆聽",
            statusHandsFree: "免持",
            statusTranscribing: "正在轉寫",
            statusPolishing: "正在整理",
            statusPasted: "已貼上",
            statusCopied: "已拷貝",
            statusNotPasted: "未貼上到任何位置",
            noteSecureInput: "密碼欄位正在使用中，因此文字已拷貝而非貼上。",
            noteNoAccessibility: "已拷貝。允許「輔助使用」後，聽寫就能自行貼上。",
            errorMicrophoneDenied: "麥克風取用權限已關閉。請在「系統設定」›「隱私權與安全性」›「麥克風」中允許。",
            errorMicrophoneUnavailable: "無法啟動麥克風。",
            errorEndpointInvalid: "伺服器位址必須在這台 Mac 上。",
            errorTranscriptionFailed: "轉寫失敗。",
            errorNoSpeech: "沒有聽到語音。",
            historySearch: "搜尋聽寫",
            historyEmpty: "還沒有聽寫紀錄。",
            historyNoResults: "沒有符合的聽寫。",
            historyDelete: "刪除")
        case .zhHK: return DictationStrings(
            pageTitle: "聽寫",
            hubDescription: "按住快捷鍵說話，文字就會輸入到游標所在位置。使用 whisper.cpp 在這部 Mac 上轉寫。",
            enableToggle: "用快捷鍵聽寫",
            settingsCaption: "說話時按住 Fn，放開即插入文字；連按兩次 Fn 則以免提方式持續聆聽，直到再次按下。下方的快捷鍵用法相同。按 Esc 取消。",
            fnHint: "若要讓 Fn 用於聽寫，請在「系統設定」›「鍵盤」中將「按下 🌐 鍵時」設為「不執行任何動作」。",
            privacyNote: "音訊與文字絕不會離開這部 Mac：whisper.cpp 在本機轉寫，整理使用與剪貼簿 AI 相同的本機模型。",
            engineHeading: "轉寫引擎",
            engineReady: "就緒，正在使用 %@",
            engineExternal: "正在使用已在 %@ 運行的伺服器",
            engineStopped: "第一次聽寫時啟動，閒置一段時間後停止。",
            engineStarting: "正在載入模型",
            engineMissingBinary: "尚未安裝 whisper.cpp。請在「終端機」執行「brew install whisper-cpp」。",
            engineMissingModel: "%@ 沒有模型檔案。請下載一個或選擇其他檔案。",
            engineFailed: "轉寫引擎無法啟動。",
            modelLabel: "模型檔案",
            chooseModel: "選擇…",
            downloadModel: "下載模型",
            endpointLabel: "伺服器",
            check: "檢查",
            languageLabel: "說話語言",
            languageSystem: "與這部 Mac 相同",
            languageAuto: "自動偵測",
            polishLabel: "AI 整理",
            polishOff: "關閉",
            polishSmart: "有幫助時",
            polishAlways: "永遠",
            polishCaption: "移除猶豫與說錯的開頭，只保留你最後的更正，並排好列表。「有幫助時」會對乾淨的句子略過模型，立即貼上。",
            vocabularyLabel: "詞彙表",
            vocabularyPlaceholder: "名稱、產品、術語，以逗號分隔",
            vocabularyCaption: "在轉寫與整理中都完全依照這裡的寫法。",
            lastDictation: "上次聽寫",
            copy: "複製",
            statusListening: "正在聆聽",
            statusHandsFree: "免提",
            statusTranscribing: "正在轉寫",
            statusPolishing: "正在整理",
            statusPasted: "已貼上",
            statusCopied: "已複製",
            statusNotPasted: "未貼上到任何位置",
            noteSecureInput: "密碼欄位正在使用中，因此文字已複製而非貼上。",
            noteNoAccessibility: "已複製。允許「輔助使用」後，聽寫就能自行貼上。",
            errorMicrophoneDenied: "咪高峰取用權限已關閉。請在「系統設定」›「私隱與安全性」›「咪高峰」中允許。",
            errorMicrophoneUnavailable: "無法啟動咪高峰。",
            errorEndpointInvalid: "伺服器位址必須在這部 Mac 上。",
            errorTranscriptionFailed: "轉寫失敗。",
            errorNoSpeech: "沒有聽到語音。",
            historySearch: "搜尋聽寫",
            historyEmpty: "仲未有聽寫紀錄。",
            historyNoResults: "冇符合嘅聽寫。",
            historyDelete: "刪除")
        }
    }
}
