// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 AltF4 contributors

import Foundation

struct ClipboardAIStrings {
    let title: String
    let menuLabel: String

    let actionTranslate: String
    let actionSummarize: String
    let actionReformat: String
    let actionExtract: String
    let actionExplain: String
    let actionExplainCode: String
    let toneMenu: String
    let toneFormal: String
    let toneCasual: String
    let toneDirect: String

    let sourceHeading: String
    let resultHeading: String
    let statusThinking: String
    let statusWriting: String
    let stop: String
    let retry: String
    let copyResult: String
    let copied: String
    let replaceEntry: String
    let replaced: String

    let errorDisabled: String
    let errorRunnerUnreachable: String
    /// %@ is the model name.
    let errorModelMissing: String
    /// %@ is the host the endpoint points at.
    let errorEndpointNotLocal: String
    let errorConfigInvalid: String
    let errorInputEmpty: String
    /// %d is the minimum number of characters.
    let errorInputTooShort: String
    /// %1$d is the limit, %2$d what the entry actually holds.
    let errorInputTooLong: String
    /// %@ is one of the four nouns below.
    let errorSensitive: String
    let sensitivePrivateKey: String
    let sensitiveApiToken: String
    let sensitiveCreditCard: String
    let sensitiveCredential: String
    let errorModelFailed: String
    let errorGuardrail: String
    let errorCancelled: String

    let settingsEnable: String
    let settingsCaption: String
    let settingsLocalNote: String
    let settingsModel: String
    let settingsTargetLanguage: String
    let settingsTargetLanguagePlaceholder: String
    let settingsEndpoint: String
    let settingsBlockSensitive: String
    let settingsBlockSensitiveCaption: String
    let statusNoRunner: String
    /// %@ is the model name.
    let statusReady: String
    /// %@ is the model name.
    let statusModelNotInstalled: String
    let check: String
}

extension FeatureStrings {
    static func clipboardAI(_ language: AppLanguage) -> ClipboardAIStrings {
        switch language {
        case .enUS: return ClipboardAIStrings(
            title: "Clipboard AI",
            menuLabel: "AI",
            actionTranslate: "Translate",
            actionSummarize: "Summarise",
            actionReformat: "Clean up",
            actionExtract: "Extract details",
            actionExplain: "Explain",
            actionExplainCode: "Explain code or error",
            toneMenu: "Change tone",
            toneFormal: "Formal",
            toneCasual: "Casual",
            toneDirect: "Direct",
            sourceHeading: "Original",
            resultHeading: "Result",
            statusThinking: "Loading the model",
            statusWriting: "Writing",
            stop: "Stop",
            retry: "Try again",
            copyResult: "Copy",
            copied: "Copied",
            replaceEntry: "Replace entry",
            replaced: "Replaced",
            errorDisabled: "Clipboard AI is turned off.",
            errorRunnerUnreachable: "No model runner is answering. Install Ollama and run “ollama serve”.",
            errorModelMissing: "The model “%1$@” is not installed. Run “ollama pull %1$@” to get it.",
            errorEndpointNotLocal: "The endpoint points at “%@”, which is not this Mac. Nothing was sent.",
            errorConfigInvalid: "The model name or the endpoint is not valid. Check both in Settings.",
            errorInputEmpty: "There is nothing to work on.",
            errorInputTooShort: "This entry is too short for that. It needs at least %d characters.",
            errorInputTooLong: "This entry is too long. The limit is %1$d characters and it holds %2$d.",
            errorSensitive: "This entry was not sent: it looks like it contains %@.",
            sensitivePrivateKey: "a private key",
            sensitiveApiToken: "an API token",
            sensitiveCreditCard: "a card number",
            sensitiveCredential: "a password or a key",
            errorModelFailed: "The model runner could not answer.",
            errorGuardrail: "The answer did not pass the safety checks, so it was discarded.",
            errorCancelled: "Stopped.",
            settingsEnable: "Clipboard AI",
            settingsCaption: "Adds translate, summarise, clean up, extract, explain and tone changes to any saved text entry. The result opens in the Dynamic Island, where you choose what to do with it.",
            settingsLocalNote: "Runs a model on this Mac through Ollama. Nothing leaves the machine: an endpoint that is not on this Mac is refused.",
            settingsModel: "Model",
            settingsTargetLanguage: "Translate into",
            settingsTargetLanguagePlaceholder: "This Mac’s language",
            settingsEndpoint: "Endpoint",
            settingsBlockSensitive: "Never send passwords or keys",
            settingsBlockSensitiveCaption: "Refuses entries that look like private keys, API tokens, card numbers or password lines, before any request is made.",
            statusNoRunner: "No model runner is answering",
            statusReady: "Ready, using %@",
            statusModelNotInstalled: "The runner is up, but “%@” is not installed",
            check: "Check")
        case .ptBR: return ClipboardAIStrings(
            title: "IA do clipboard",
            menuLabel: "IA",
            actionTranslate: "Traduzir",
            actionSummarize: "Resumir",
            actionReformat: "Corrigir",
            actionExtract: "Extrair dados",
            actionExplain: "Explicar",
            actionExplainCode: "Explicar código ou erro",
            toneMenu: "Mudar o tom",
            toneFormal: "Formal",
            toneCasual: "Informal",
            toneDirect: "Direto",
            sourceHeading: "Original",
            resultHeading: "Resultado",
            statusThinking: "Carregando o modelo",
            statusWriting: "Escrevendo",
            stop: "Parar",
            retry: "Tentar novamente",
            copyResult: "Copiar",
            copied: "Copiado",
            replaceEntry: "Substituir o item",
            replaced: "Substituído",
            errorDisabled: "A IA do clipboard está desativada.",
            errorRunnerUnreachable: "Nenhum motor de modelos está respondendo. Instale o Ollama e execute “ollama serve”.",
            errorModelMissing: "O modelo “%1$@” não está instalado. Execute “ollama pull %1$@” para obtê-lo.",
            errorEndpointNotLocal: "O ponto de conexão aponta para “%@”, que não é este Mac. Nada foi enviado.",
            errorConfigInvalid: "O nome do modelo ou o ponto de conexão não é válido. Verifique os dois nos ajustes.",
            errorInputEmpty: "Não há nada para processar.",
            errorInputTooShort: "Este item é curto demais para isso. São necessários pelo menos %d caracteres.",
            errorInputTooLong: "Este item é longo demais. O limite é de %1$d caracteres e ele tem %2$d.",
            errorSensitive: "Este item não foi enviado: parece conter %@.",
            sensitivePrivateKey: "uma chave privada",
            sensitiveApiToken: "um token de API",
            sensitiveCreditCard: "um número de cartão",
            sensitiveCredential: "uma senha ou uma chave",
            errorModelFailed: "O motor de modelos não conseguiu responder.",
            errorGuardrail: "A resposta não passou nas verificações de segurança e foi descartada.",
            errorCancelled: "Interrompido.",
            settingsEnable: "IA do clipboard",
            settingsCaption: "Adiciona traduzir, resumir, corrigir, extrair, explicar e mudanças de tom a qualquer texto guardado. O resultado abre no Dynamic Island, onde você decide o que fazer com ele.",
            settingsLocalNote: "Executa um modelo neste Mac através do Ollama. Nada sai da máquina: um ponto de conexão que não esteja neste Mac é recusado.",
            settingsModel: "Modelo",
            settingsTargetLanguage: "Traduzir para",
            settingsTargetLanguagePlaceholder: "O idioma deste Mac",
            settingsEndpoint: "Ponto de conexão",
            settingsBlockSensitive: "Nunca enviar senhas nem chaves",
            settingsBlockSensitiveCaption: "Recusa itens que pareçam chaves privadas, tokens de API, números de cartão ou linhas de senha, antes de qualquer requisição.",
            statusNoRunner: "Nenhum motor de modelos está respondendo",
            statusReady: "Pronto, usando %@",
            statusModelNotInstalled: "O motor está ativo, mas “%@” não está instalado",
            check: "Verificar")
        case .tr: return ClipboardAIStrings(
            title: "Pano yapay zekâsı",
            menuLabel: "Yapay zekâ",
            actionTranslate: "Çevir",
            actionSummarize: "Özetle",
            actionReformat: "Düzelt",
            actionExtract: "Ayrıntıları çıkar",
            actionExplain: "Açıkla",
            actionExplainCode: "Kodu veya hatayı açıkla",
            toneMenu: "Tonu değiştir",
            toneFormal: "Resmî",
            toneCasual: "Samimi",
            toneDirect: "Doğrudan",
            sourceHeading: "Özgün metin",
            resultHeading: "Sonuç",
            statusThinking: "Model yükleniyor",
            statusWriting: "Yazılıyor",
            stop: "Durdur",
            retry: "Yeniden dene",
            copyResult: "Kopyala",
            copied: "Kopyalandı",
            replaceEntry: "Öğeyi değiştir",
            replaced: "Değiştirildi",
            errorDisabled: "Pano yapay zekâsı kapalı.",
            errorRunnerUnreachable: "Yanıt veren bir model motoru yok. Ollama’yı kurun ve “ollama serve” komutunu çalıştırın.",
            errorModelMissing: "“%1$@” modeli kurulu değil. Almak için “ollama pull %1$@” komutunu çalıştırın.",
            errorEndpointNotLocal: "Uç nokta “%@” adresini gösteriyor; burası bu Mac değil. Hiçbir şey gönderilmedi.",
            errorConfigInvalid: "Model adı veya uç nokta geçerli değil. İkisini de Ayarlar’da denetleyin.",
            errorInputEmpty: "Üzerinde çalışılacak bir şey yok.",
            errorInputTooShort: "Bu öğe bunun için çok kısa. En az %d karakter gerekiyor.",
            errorInputTooLong: "Bu öğe çok uzun. Sınır %1$d karakter, bu öğede ise %2$d karakter var.",
            errorSensitive: "Bu öğe gönderilmedi: %@ içeriyor gibi görünüyor.",
            sensitivePrivateKey: "özel anahtar",
            sensitiveApiToken: "API token",
            sensitiveCreditCard: "kart numarası",
            sensitiveCredential: "parola veya anahtar",
            errorModelFailed: "Model motoru yanıt veremedi.",
            errorGuardrail: "Yanıt güvenlik denetimlerinden geçemedi ve atıldı.",
            errorCancelled: "Durduruldu.",
            settingsEnable: "Pano yapay zekâsı",
            settingsCaption: "Kaydedilmiş herhangi bir metne çevirme, özetleme, düzeltme, ayrıntı çıkarma, açıklama ve ton değiştirme ekler. Sonuç çentikte açılır; ne yapacağınıza orada karar verirsiniz.",
            settingsLocalNote: "Ollama üzerinden bu Mac’te bir model çalıştırır. Hiçbir şey makineden çıkmaz: bu Mac’te olmayan bir uç nokta reddedilir.",
            settingsModel: "Model",
            settingsTargetLanguage: "Şu dile çevir",
            settingsTargetLanguagePlaceholder: "Bu Mac’in dili",
            settingsEndpoint: "Uç nokta",
            settingsBlockSensitive: "Parolaları ve anahtarları asla gönderme",
            settingsBlockSensitiveCaption: "Özel anahtar, API token, kart numarası veya parola satırı gibi görünen öğeleri, herhangi bir istek gönderilmeden önce reddeder.",
            statusNoRunner: "Yanıt veren bir model motoru yok",
            statusReady: "Hazır, %@ kullanılıyor",
            statusModelNotInstalled: "Motor çalışıyor ama “%@” kurulu değil",
            check: "Denetle")
        case .ru: return ClipboardAIStrings(
            title: "ИИ в буфере обмена",
            menuLabel: "ИИ",
            actionTranslate: "Перевести",
            actionSummarize: "Кратко изложить",
            actionReformat: "Исправить",
            actionExtract: "Извлечь данные",
            actionExplain: "Объяснить",
            actionExplainCode: "Объяснить код или ошибку",
            toneMenu: "Изменить тон",
            toneFormal: "Формальный",
            toneCasual: "Неформальный",
            toneDirect: "Прямой",
            sourceHeading: "Оригинал",
            resultHeading: "Результат",
            statusThinking: "Загрузка модели",
            statusWriting: "Пишет",
            stop: "Остановить",
            retry: "Повторить",
            copyResult: "Скопировать",
            copied: "Скопировано",
            replaceEntry: "Заменить элемент",
            replaced: "Заменено",
            errorDisabled: "ИИ в буфере обмена отключён.",
            errorRunnerUnreachable: "Движок моделей не отвечает. Установите Ollama и выполните «ollama serve».",
            errorModelMissing: "Модель «%1$@» не установлена. Выполните «ollama pull %1$@», чтобы загрузить её.",
            errorEndpointNotLocal: "Адрес подключения ведёт на «%@», а это не ваш Mac. Ничего не отправлено.",
            errorConfigInvalid: "Имя модели или адрес подключения недействительны. Проверьте оба значения в настройках.",
            errorInputEmpty: "Обрабатывать нечего.",
            errorInputTooShort: "Этот элемент слишком короткий для этого. Нужно не менее %d символов.",
            errorInputTooLong: "Этот элемент слишком длинный. Предел составляет %1$d символов, а в нём %2$d.",
            errorSensitive: "Этот элемент не отправлен: похоже, он содержит %@.",
            sensitivePrivateKey: "закрытый ключ",
            sensitiveApiToken: "токен API",
            sensitiveCreditCard: "номер карты",
            sensitiveCredential: "пароль или ключ",
            errorModelFailed: "Движок моделей не смог ответить.",
            errorGuardrail: "Ответ не прошёл проверки безопасности и был отброшен.",
            errorCancelled: "Остановлено.",
            settingsEnable: "ИИ в буфере обмена",
            settingsCaption: "Добавляет перевод, краткое изложение, исправление, извлечение данных, объяснение и смену тона для любой сохранённой записи. Результат открывается в вырезе, где вы решаете, что с ним делать.",
            settingsLocalNote: "Запускает модель на этом Mac через Ollama. Ничего не покидает компьютер: адрес подключения за пределами этого Mac отклоняется.",
            settingsModel: "Модель",
            settingsTargetLanguage: "Переводить на",
            settingsTargetLanguagePlaceholder: "Язык этого Mac",
            settingsEndpoint: "Адрес подключения",
            settingsBlockSensitive: "Никогда не отправлять пароли и ключи",
            settingsBlockSensitiveCaption: "Отклоняет элементы, похожие на закрытые ключи, токены API, номера карт или строки с паролями, ещё до отправки запроса.",
            statusNoRunner: "Движок моделей не отвечает",
            statusReady: "Готово, используется %@",
            statusModelNotInstalled: "Движок работает, но «%@» не установлена",
            check: "Проверить")
        case .es: return ClipboardAIStrings(
            title: "IA del portapapeles",
            menuLabel: "IA",
            actionTranslate: "Traducir",
            actionSummarize: "Resumir",
            actionReformat: "Corregir",
            actionExtract: "Extraer datos",
            actionExplain: "Explicar",
            actionExplainCode: "Explicar código o error",
            toneMenu: "Cambiar el tono",
            toneFormal: "Formal",
            toneCasual: "Cercano",
            toneDirect: "Directo",
            sourceHeading: "Original",
            resultHeading: "Resultado",
            statusThinking: "Cargando el modelo",
            statusWriting: "Escribiendo",
            stop: "Detener",
            retry: "Reintentar",
            copyResult: "Copiar",
            copied: "Copiado",
            replaceEntry: "Sustituir la entrada",
            replaced: "Sustituida",
            errorDisabled: "La IA del portapapeles está desactivada.",
            errorRunnerUnreachable: "No responde ningún motor de modelos. Instala Ollama y ejecuta “ollama serve”.",
            errorModelMissing: "El modelo “%1$@” no está instalado. Ejecuta “ollama pull %1$@” para obtenerlo.",
            errorEndpointNotLocal: "El punto de conexión apunta a “%@”, que no es este Mac. No se envió nada.",
            errorConfigInvalid: "El nombre del modelo o el punto de conexión no son válidos. Revisa ambos en los ajustes.",
            errorInputEmpty: "No hay nada sobre lo que trabajar.",
            errorInputTooShort: "Esta entrada es demasiado corta para eso. Necesita al menos %d caracteres.",
            errorInputTooLong: "Esta entrada es demasiado larga. El límite son %1$d caracteres y tiene %2$d.",
            errorSensitive: "Esta entrada no se envió: parece contener %@.",
            sensitivePrivateKey: "una clave privada",
            sensitiveApiToken: "un token de API",
            sensitiveCreditCard: "un número de tarjeta",
            sensitiveCredential: "una contraseña o una clave",
            errorModelFailed: "El motor de modelos no pudo responder.",
            errorGuardrail: "La respuesta no superó las comprobaciones de seguridad y se descartó.",
            errorCancelled: "Detenido.",
            settingsEnable: "IA del portapapeles",
            settingsCaption: "Añade traducir, resumir, corregir, extraer, explicar y cambios de tono a cualquier entrada de texto guardada. El resultado se abre en el Dynamic Island, donde decides qué hacer con él.",
            settingsLocalNote: "Ejecuta un modelo en este Mac a través de Ollama. Nada sale de la máquina: se rechaza cualquier punto de conexión que no esté en este Mac.",
            settingsModel: "Modelo",
            settingsTargetLanguage: "Traducir a",
            settingsTargetLanguagePlaceholder: "El idioma de este Mac",
            settingsEndpoint: "Punto de conexión",
            settingsBlockSensitive: "No enviar nunca contraseñas ni claves",
            settingsBlockSensitiveCaption: "Rechaza las entradas que parecen claves privadas, tokens de API, números de tarjeta o líneas de contraseña, antes de hacer ninguna petición.",
            statusNoRunner: "No responde ningún motor de modelos",
            statusReady: "Listo, usando %@",
            statusModelNotInstalled: "El motor funciona, pero “%@” no está instalado",
            check: "Comprobar")
        case .de: return ClipboardAIStrings(
            title: "KI für die Zwischenablage",
            menuLabel: "KI",
            actionTranslate: "Übersetzen",
            actionSummarize: "Zusammenfassen",
            actionReformat: "Bereinigen",
            actionExtract: "Details extrahieren",
            actionExplain: "Erklären",
            actionExplainCode: "Code oder Fehler erklären",
            toneMenu: "Ton ändern",
            toneFormal: "Förmlich",
            toneCasual: "Locker",
            toneDirect: "Direkt",
            sourceHeading: "Original",
            resultHeading: "Ergebnis",
            statusThinking: "Modell wird geladen",
            statusWriting: "Schreibt",
            stop: "Stoppen",
            retry: "Erneut versuchen",
            copyResult: "Kopieren",
            copied: "Kopiert",
            replaceEntry: "Eintrag ersetzen",
            replaced: "Ersetzt",
            errorDisabled: "Die KI für die Zwischenablage ist ausgeschaltet.",
            errorRunnerUnreachable: "Kein Modelldienst antwortet. Installiere Ollama und führe „ollama serve“ aus.",
            errorModelMissing: "Das Modell „%1$@“ ist nicht installiert. Führe „ollama pull %1$@“ aus, um es zu laden.",
            errorEndpointNotLocal: "Der Endpunkt zeigt auf „%@“, und das ist nicht dieser Mac. Es wurde nichts gesendet.",
            errorConfigInvalid: "Der Modellname oder der Endpunkt ist ungültig. Prüfe beides in den Einstellungen.",
            errorInputEmpty: "Es gibt nichts zu bearbeiten.",
            errorInputTooShort: "Dieser Eintrag ist dafür zu kurz. Er braucht mindestens %d Zeichen.",
            errorInputTooLong: "Dieser Eintrag ist zu lang. Das Limit liegt bei %1$d Zeichen, er enthält %2$d.",
            errorSensitive: "Dieser Eintrag wurde nicht gesendet: Er sieht nach %@ aus.",
            sensitivePrivateKey: "einem privaten Schlüssel",
            sensitiveApiToken: "einem API-Token",
            sensitiveCreditCard: "einer Kartennummer",
            sensitiveCredential: "einem Passwort oder Schlüssel",
            errorModelFailed: "Der Modelldienst konnte nicht antworten.",
            errorGuardrail: "Die Antwort hat die Sicherheitsprüfungen nicht bestanden und wurde verworfen.",
            errorCancelled: "Gestoppt.",
            settingsEnable: "KI für die Zwischenablage",
            settingsCaption: "Ergänzt jeden gesicherten Texteintrag um Übersetzen, Zusammenfassen, Bereinigen, Extrahieren, Erklären und Tonwechsel. Das Ergebnis öffnet sich in der Dynamic Island, wo du entscheidest, was damit passiert.",
            settingsLocalNote: "Führt ein Modell über Ollama auf diesem Mac aus. Nichts verlässt den Rechner: Ein Endpunkt, der nicht auf diesem Mac liegt, wird abgelehnt.",
            settingsModel: "Modell",
            settingsTargetLanguage: "Übersetzen in",
            settingsTargetLanguagePlaceholder: "Sprache dieses Macs",
            settingsEndpoint: "Endpunkt",
            settingsBlockSensitive: "Passwörter und Schlüssel nie senden",
            settingsBlockSensitiveCaption: "Weist Einträge, die wie private Schlüssel, API-Token, Kartennummern oder Passwortzeilen aussehen, schon vor jeder Anfrage zurück.",
            statusNoRunner: "Kein Modelldienst antwortet",
            statusReady: "Bereit, verwendet %@",
            statusModelNotInstalled: "Der Dienst läuft, aber „%@“ ist nicht installiert",
            check: "Prüfen")
        case .fr: return ClipboardAIStrings(
            title: "IA du presse-papiers",
            menuLabel: "IA",
            actionTranslate: "Traduire",
            actionSummarize: "Résumer",
            actionReformat: "Corriger",
            actionExtract: "Extraire les détails",
            actionExplain: "Expliquer",
            actionExplainCode: "Expliquer le code ou l’erreur",
            toneMenu: "Changer de ton",
            toneFormal: "Formel",
            toneCasual: "Décontracté",
            toneDirect: "Direct",
            sourceHeading: "Original",
            resultHeading: "Résultat",
            statusThinking: "Chargement du modèle",
            statusWriting: "Rédaction",
            stop: "Arrêter",
            retry: "Réessayer",
            copyResult: "Copier",
            copied: "Copié",
            replaceEntry: "Remplacer l’élément",
            replaced: "Remplacé",
            errorDisabled: "L’IA du presse-papiers est désactivée.",
            errorRunnerUnreachable: "Aucun moteur de modèles ne répond. Installez Ollama et exécutez «\u{00A0}ollama serve\u{00A0}».",
            errorModelMissing: "Le modèle «\u{00A0}%1$@\u{00A0}» n’est pas installé. Exécutez «\u{00A0}ollama pull %1$@\u{00A0}» pour l’obtenir.",
            errorEndpointNotLocal: "Le point de terminaison pointe vers «\u{00A0}%@\u{00A0}», qui n’est pas ce Mac. Rien n’a été envoyé.",
            errorConfigInvalid: "Le nom du modèle ou le point de terminaison n’est pas valide. Vérifiez les deux dans les Réglages.",
            errorInputEmpty: "Il n’y a rien à traiter.",
            errorInputTooShort: "Cet élément est trop court pour cela. Il faut au moins %d caractères.",
            errorInputTooLong: "Cet élément est trop long. La limite est de %1$d caractères et il en contient %2$d.",
            errorSensitive: "Cet élément n’a pas été envoyé\u{00A0}: il semble contenir %@.",
            sensitivePrivateKey: "une clé privée",
            sensitiveApiToken: "un jeton d’API",
            sensitiveCreditCard: "un numéro de carte",
            sensitiveCredential: "un mot de passe ou une clé",
            errorModelFailed: "Le moteur de modèles n’a pas pu répondre.",
            errorGuardrail: "La réponse n’a pas passé les contrôles de sécurité, elle a donc été écartée.",
            errorCancelled: "Arrêté.",
            settingsEnable: "IA du presse-papiers",
            settingsCaption: "Ajoute traduire, résumer, corriger, extraire, expliquer et changer de ton à n’importe quel texte enregistré. Le résultat s’ouvre dans le Dynamic Island, où vous choisissez quoi en faire.",
            settingsLocalNote: "Exécute un modèle sur ce Mac via Ollama. Rien ne quitte la machine\u{00A0}: un point de terminaison qui n’est pas sur ce Mac est refusé.",
            settingsModel: "Modèle",
            settingsTargetLanguage: "Traduire en",
            settingsTargetLanguagePlaceholder: "La langue de ce Mac",
            settingsEndpoint: "Point de terminaison",
            settingsBlockSensitive: "Ne jamais envoyer de mots de passe ni de clés",
            settingsBlockSensitiveCaption: "Refuse les éléments qui ressemblent à des clés privées, jetons d’API, numéros de carte ou lignes de mot de passe, avant toute requête.",
            statusNoRunner: "Aucun moteur de modèles ne répond",
            statusReady: "Prêt, avec %@",
            statusModelNotInstalled: "Le moteur fonctionne, mais «\u{00A0}%@\u{00A0}» n’est pas installé",
            check: "Vérifier")
        case .it: return ClipboardAIStrings(
            title: "IA degli appunti",
            menuLabel: "IA",
            actionTranslate: "Traduci",
            actionSummarize: "Riassumi",
            actionReformat: "Correggi",
            actionExtract: "Estrai i dettagli",
            actionExplain: "Spiega",
            actionExplainCode: "Spiega codice o errore",
            toneMenu: "Cambia tono",
            toneFormal: "Formale",
            toneCasual: "Informale",
            toneDirect: "Diretto",
            sourceHeading: "Originale",
            resultHeading: "Risultato",
            statusThinking: "Caricamento del modello",
            statusWriting: "Sta scrivendo",
            stop: "Interrompi",
            retry: "Riprova",
            copyResult: "Copia",
            copied: "Copiato",
            replaceEntry: "Sostituisci elemento",
            replaced: "Sostituito",
            errorDisabled: "L’IA degli appunti è disattivata.",
            errorRunnerUnreachable: "Nessun motore dei modelli risponde. Installa Ollama ed esegui “ollama serve”.",
            errorModelMissing: "Il modello “%1$@” non è installato. Esegui “ollama pull %1$@” per ottenerlo.",
            errorEndpointNotLocal: "Il punto di connessione punta a “%@”, che non è questo Mac. Non è stato inviato nulla.",
            errorConfigInvalid: "Il nome del modello o il punto di connessione non è valido. Controlla entrambi nelle Impostazioni.",
            errorInputEmpty: "Non c’è nulla su cui lavorare.",
            errorInputTooShort: "Questo elemento è troppo corto per farlo. Servono almeno %d caratteri.",
            errorInputTooLong: "Questo elemento è troppo lungo. Il limite è di %1$d caratteri e ne contiene %2$d.",
            errorSensitive: "Questo elemento non è stato inviato: sembra contenere %@.",
            sensitivePrivateKey: "una chiave privata",
            sensitiveApiToken: "un token API",
            sensitiveCreditCard: "un numero di carta",
            sensitiveCredential: "una password o una chiave",
            errorModelFailed: "Il motore dei modelli non è riuscito a rispondere.",
            errorGuardrail: "La risposta non ha superato i controlli di sicurezza ed è stata scartata.",
            errorCancelled: "Interrotto.",
            settingsEnable: "IA degli appunti",
            settingsCaption: "Aggiunge traduci, riassumi, correggi, estrai, spiega e cambio di tono a qualsiasi testo salvato. Il risultato si apre nel Dynamic Island, dove decidi cosa farne.",
            settingsLocalNote: "Esegue un modello su questo Mac tramite Ollama. Nulla lascia la macchina: un punto di connessione che non si trova su questo Mac viene rifiutato.",
            settingsModel: "Modello",
            settingsTargetLanguage: "Traduci in",
            settingsTargetLanguagePlaceholder: "La lingua di questo Mac",
            settingsEndpoint: "Punto di connessione",
            settingsBlockSensitive: "Non inviare mai password o chiavi",
            settingsBlockSensitiveCaption: "Rifiuta gli elementi che sembrano chiavi private, token API, numeri di carta o righe di password, prima di qualsiasi richiesta.",
            statusNoRunner: "Nessun motore dei modelli risponde",
            statusReady: "Pronto, con %@",
            statusModelNotInstalled: "Il motore è attivo, ma “%@” non è installato",
            check: "Controlla")
        case .ja: return ClipboardAIStrings(
            title: "クリップボード AI",
            menuLabel: "AI",
            actionTranslate: "翻訳",
            actionSummarize: "要約",
            actionReformat: "整える",
            actionExtract: "情報を抽出",
            actionExplain: "説明",
            actionExplainCode: "コードやエラーを説明",
            toneMenu: "トーンを変更",
            toneFormal: "フォーマル",
            toneCasual: "カジュアル",
            toneDirect: "ストレート",
            sourceHeading: "元のテキスト",
            resultHeading: "結果",
            statusThinking: "モデルを読み込み中",
            statusWriting: "生成中",
            stop: "停止",
            retry: "再試行",
            copyResult: "コピー",
            copied: "コピー済み",
            replaceEntry: "項目を置き換える",
            replaced: "置き換えました",
            errorDisabled: "クリップボード AI はオフになっています。",
            errorRunnerUnreachable: "モデルの実行エンジンが応答していません。Ollama をインストールして「ollama serve」を実行してください。",
            errorModelMissing: "モデル「%1$@」がインストールされていません。「ollama pull %1$@」を実行して入手してください。",
            errorEndpointNotLocal: "接続先が「%@」を指しており、この Mac ではありません。何も送信していません。",
            errorConfigInvalid: "モデル名または接続先が正しくありません。設定で両方を確認してください。",
            errorInputEmpty: "処理する内容がありません。",
            errorInputTooShort: "この項目は短すぎます。少なくとも %d 文字が必要です。",
            errorInputTooLong: "この項目は長すぎます。上限は %1$d 文字ですが、%2$d 文字あります。",
            errorSensitive: "この項目は送信されませんでした。%@が含まれているようです。",
            sensitivePrivateKey: "秘密鍵",
            sensitiveApiToken: "API トークン",
            sensitiveCreditCard: "カード番号",
            sensitiveCredential: "パスワードまたはキー",
            errorModelFailed: "モデルの実行エンジンが応答できませんでした。",
            errorGuardrail: "回答が安全性チェックを通らなかったため、破棄しました。",
            errorCancelled: "停止しました。",
            settingsEnable: "クリップボード AI",
            settingsCaption: "保存済みのテキスト項目に、翻訳、要約、整形、抽出、説明、トーン変更を追加します。結果はDynamic Islandに開き、そこで扱いを選べます。",
            settingsLocalNote: "Ollama を通じてこの Mac 上でモデルを実行します。何もこの Mac から出ません。この Mac にない接続先は拒否されます。",
            settingsModel: "モデル",
            settingsTargetLanguage: "翻訳先の言語",
            settingsTargetLanguagePlaceholder: "この Mac の言語",
            settingsEndpoint: "接続先",
            settingsBlockSensitive: "パスワードやキーは送信しない",
            settingsBlockSensitiveCaption: "秘密鍵、API トークン、カード番号、パスワードらしい行に見える項目を、リクエストを送る前に拒否します。",
            statusNoRunner: "モデルの実行エンジンが応答していません",
            statusReady: "準備完了。%@ を使用中",
            statusModelNotInstalled: "実行エンジンは動作していますが、「%@」がインストールされていません",
            check: "確認")
        case .ko: return ClipboardAIStrings(
            title: "클립보드 AI",
            menuLabel: "AI",
            actionTranslate: "번역",
            actionSummarize: "요약",
            actionReformat: "정리",
            actionExtract: "정보 추출",
            actionExplain: "설명",
            actionExplainCode: "코드 또는 오류 설명",
            toneMenu: "어조 바꾸기",
            toneFormal: "격식",
            toneCasual: "친근",
            toneDirect: "직설",
            sourceHeading: "원본",
            resultHeading: "결과",
            statusThinking: "모델 불러오는 중",
            statusWriting: "작성 중",
            stop: "중단",
            retry: "다시 시도",
            copyResult: "복사",
            copied: "복사됨",
            replaceEntry: "항목 바꾸기",
            replaced: "바뀜",
            errorDisabled: "클립보드 AI가 꺼져 있습니다.",
            errorRunnerUnreachable: "응답하는 모델 실행기가 없습니다. Ollama를 설치하고 “ollama serve”를 실행하세요.",
            errorModelMissing: "“%1$@” 모델이 설치되어 있지 않습니다. “ollama pull %1$@”를 실행해 받으세요.",
            errorEndpointNotLocal: "연결 주소가 이 Mac이 아닌 “%@”에 연결됩니다. 아무것도 전송하지 않았습니다.",
            errorConfigInvalid: "모델 이름 또는 연결 주소가 올바르지 않습니다. 설정에서 둘 다 확인하세요.",
            errorInputEmpty: "처리할 내용이 없습니다.",
            errorInputTooShort: "이 항목은 그러기에는 너무 짧습니다. 최소 %d자가 필요합니다.",
            errorInputTooLong: "이 항목은 너무 깁니다. 제한은 %1$d자이며 현재 %2$d자입니다.",
            errorSensitive: "%@처럼 보이는 내용이 있어 이 항목을 전송하지 않았습니다.",
            sensitivePrivateKey: "개인 키",
            sensitiveApiToken: "API 토큰",
            sensitiveCreditCard: "카드 번호",
            sensitiveCredential: "암호 또는 키",
            errorModelFailed: "모델 실행기가 응답하지 못했습니다.",
            errorGuardrail: "답변이 안전성 검사를 통과하지 못해 폐기했습니다.",
            errorCancelled: "중단했습니다.",
            settingsEnable: "클립보드 AI",
            settingsCaption: "저장된 모든 텍스트 항목에 번역, 요약, 정리, 추출, 설명, 어조 변경을 더합니다. 결과는 Dynamic Island에 열리며, 거기서 무엇을 할지 고릅니다.",
            settingsLocalNote: "Ollama를 통해 이 Mac에서 모델을 실행합니다. 아무것도 기기를 벗어나지 않으며, 이 Mac이 아닌 연결 주소는 거부됩니다.",
            settingsModel: "모델",
            settingsTargetLanguage: "번역할 언어",
            settingsTargetLanguagePlaceholder: "이 Mac의 언어",
            settingsEndpoint: "연결 주소",
            settingsBlockSensitive: "암호나 키는 전송하지 않기",
            settingsBlockSensitiveCaption: "개인 키, API 토큰, 카드 번호, 암호 줄처럼 보이는 항목은 요청을 보내기 전에 거부합니다.",
            statusNoRunner: "응답하는 모델 실행기가 없습니다",
            statusReady: "준비됨, %@ 사용 중",
            statusModelNotInstalled: "실행기는 작동 중이지만 “%@”가 설치되어 있지 않습니다",
            check: "확인")
        case .zhHans: return ClipboardAIStrings(
            title: "剪贴板 AI",
            menuLabel: "AI",
            actionTranslate: "翻译",
            actionSummarize: "总结",
            actionReformat: "整理",
            actionExtract: "提取信息",
            actionExplain: "解释",
            actionExplainCode: "解释代码或报错",
            toneMenu: "更改语气",
            toneFormal: "正式",
            toneCasual: "轻松",
            toneDirect: "直接",
            sourceHeading: "原文",
            resultHeading: "结果",
            statusThinking: "正在加载模型",
            statusWriting: "正在生成",
            stop: "停止",
            retry: "重试",
            copyResult: "拷贝",
            copied: "已拷贝",
            replaceEntry: "替换项目",
            replaced: "已替换",
            errorDisabled: "剪贴板 AI 已关闭。",
            errorRunnerUnreachable: "没有模型运行程序在响应。请安装 Ollama 并运行“ollama serve”。",
            errorModelMissing: "模型“%1$@”尚未安装。请运行“ollama pull %1$@”来获取。",
            errorEndpointNotLocal: "连接地址指向“%@”，那不是这台 Mac。没有发送任何内容。",
            errorConfigInvalid: "模型名称或连接地址无效。请在设置中检查这两项。",
            errorInputEmpty: "没有可处理的内容。",
            errorInputTooShort: "此条目太短，无法这样处理。至少需要 %d 个字符。",
            errorInputTooLong: "此条目太长。上限为 %1$d 个字符，当前有 %2$d 个。",
            errorSensitive: "此条目未发送：其中似乎包含%@。",
            sensitivePrivateKey: "私钥",
            sensitiveApiToken: "API 令牌",
            sensitiveCreditCard: "卡号",
            sensitiveCredential: "密码或密钥",
            errorModelFailed: "模型运行程序无法作出回应。",
            errorGuardrail: "回答未通过安全检查，已被丢弃。",
            errorCancelled: "已停止。",
            settingsEnable: "剪贴板 AI",
            settingsCaption: "为任何已保存的文本条目添加翻译、总结、整理、提取、解释和语气调整。结果会在Dynamic Island中打开，你可以在那里决定如何处理。",
            settingsLocalNote: "通过 Ollama 在这台 Mac 上运行模型。没有任何内容离开这台电脑：不在这台 Mac 上的连接地址会被拒绝。",
            settingsModel: "模型",
            settingsTargetLanguage: "翻译成",
            settingsTargetLanguagePlaceholder: "这台 Mac 的语言",
            settingsEndpoint: "连接地址",
            settingsBlockSensitive: "绝不发送密码或密钥",
            settingsBlockSensitiveCaption: "在发出任何请求之前，拒绝看起来像私钥、API 令牌、卡号或密码行的条目。",
            statusNoRunner: "没有模型运行程序在响应",
            statusReady: "已就绪，正在使用 %@",
            statusModelNotInstalled: "运行程序已启动，但“%@”尚未安装",
            check: "检查")
        case .zhTW: return ClipboardAIStrings(
            title: "剪貼簿 AI",
            menuLabel: "AI",
            actionTranslate: "翻譯",
            actionSummarize: "總結",
            actionReformat: "整理",
            actionExtract: "擷取資訊",
            actionExplain: "解釋",
            actionExplainCode: "解釋程式碼或錯誤",
            toneMenu: "更改語氣",
            toneFormal: "正式",
            toneCasual: "輕鬆",
            toneDirect: "直接",
            sourceHeading: "原文",
            resultHeading: "結果",
            statusThinking: "正在載入模型",
            statusWriting: "正在產生",
            stop: "停止",
            retry: "重試",
            copyResult: "複製",
            copied: "已複製",
            replaceEntry: "取代項目",
            replaced: "已取代",
            errorDisabled: "剪貼簿 AI 已關閉。",
            errorRunnerUnreachable: "沒有模型執行程式回應。請安裝 Ollama 並執行「ollama serve」。",
            errorModelMissing: "模型「%1$@」尚未安裝。請執行「ollama pull %1$@」來取得。",
            errorEndpointNotLocal: "連線位址指向「%@」，那不是這台 Mac。未傳送任何內容。",
            errorConfigInvalid: "模型名稱或連線位址無效。請在設定中檢查這兩項。",
            errorInputEmpty: "沒有可處理的內容。",
            errorInputTooShort: "此項目太短，無法這樣處理。至少需要 %d 個字元。",
            errorInputTooLong: "此項目太長。上限為 %1$d 個字元，目前有 %2$d 個。",
            errorSensitive: "此項目未傳送：其中似乎包含%@。",
            sensitivePrivateKey: "私密金鑰",
            sensitiveApiToken: "API 權杖",
            sensitiveCreditCard: "卡號",
            sensitiveCredential: "密碼或金鑰",
            errorModelFailed: "模型執行程式無法回應。",
            errorGuardrail: "回應未通過安全檢查，已被捨棄。",
            errorCancelled: "已停止。",
            settingsEnable: "剪貼簿 AI",
            settingsCaption: "為任何已儲存的文字項目加入翻譯、總結、整理、擷取、解釋和語氣調整。結果會在Dynamic Island中開啟，你可以在那裡決定如何處理。",
            settingsLocalNote: "透過 Ollama 在這台 Mac 上執行模型。沒有任何內容離開這台電腦：不在這台 Mac 上的連線位址會被拒絕。",
            settingsModel: "模型",
            settingsTargetLanguage: "翻譯成",
            settingsTargetLanguagePlaceholder: "這台 Mac 的語言",
            settingsEndpoint: "連線位址",
            settingsBlockSensitive: "絕不傳送密碼或金鑰",
            settingsBlockSensitiveCaption: "在發出任何請求之前，拒絕看起來像私密金鑰、API 權杖、卡號或密碼列的項目。",
            statusNoRunner: "沒有模型執行程式回應",
            statusReady: "已就緒，正在使用 %@",
            statusModelNotInstalled: "執行程式已啟動，但「%@」尚未安裝",
            check: "檢查")
        case .zhHK: return ClipboardAIStrings(
            title: "剪貼簿 AI",
            menuLabel: "AI",
            actionTranslate: "翻譯",
            actionSummarize: "總結",
            actionReformat: "整理",
            actionExtract: "擷取資訊",
            actionExplain: "解釋",
            actionExplainCode: "解釋程式碼或錯誤",
            toneMenu: "更改語氣",
            toneFormal: "正式",
            toneCasual: "輕鬆",
            toneDirect: "直接",
            sourceHeading: "原文",
            resultHeading: "結果",
            statusThinking: "正在載入模型",
            statusWriting: "正在產生",
            stop: "停止",
            retry: "再試",
            copyResult: "複製",
            copied: "已複製",
            replaceEntry: "取代項目",
            replaced: "已取代",
            errorDisabled: "剪貼簿 AI 已關閉。",
            errorRunnerUnreachable: "沒有模型執行程式回應。請安裝 Ollama 並執行「ollama serve」。",
            errorModelMissing: "模型「%1$@」尚未安裝。請執行「ollama pull %1$@」來取得。",
            errorEndpointNotLocal: "連線位址指向「%@」，那不是這部 Mac。未傳送任何內容。",
            errorConfigInvalid: "模型名稱或連線位址無效。請在設定中檢查這兩項。",
            errorInputEmpty: "沒有可處理的內容。",
            errorInputTooShort: "此項目太短，無法這樣處理。至少需要 %d 個字元。",
            errorInputTooLong: "此項目太長。上限為 %1$d 個字元，目前有 %2$d 個。",
            errorSensitive: "此項目未傳送：其中似乎包含%@。",
            sensitivePrivateKey: "私密密鑰",
            sensitiveApiToken: "API 權杖",
            sensitiveCreditCard: "卡號",
            sensitiveCredential: "密碼或密鑰",
            errorModelFailed: "模型執行程式無法回應。",
            errorGuardrail: "回應未通過安全檢查，已被捨棄。",
            errorCancelled: "已停止。",
            settingsEnable: "剪貼簿 AI",
            settingsCaption: "為任何已儲存的文字項目加入翻譯、總結、整理、擷取、解釋和語氣調整。結果會在Dynamic Island中開啟，你可以在那裡決定如何處理。",
            settingsLocalNote: "透過 Ollama 在這部 Mac 上執行模型。沒有任何內容離開這部電腦：不在這部 Mac 上的連線位址會被拒絕。",
            settingsModel: "模型",
            settingsTargetLanguage: "翻譯成",
            settingsTargetLanguagePlaceholder: "這部 Mac 的語言",
            settingsEndpoint: "連線位址",
            settingsBlockSensitive: "絕不傳送密碼或密鑰",
            settingsBlockSensitiveCaption: "在發出任何請求之前，拒絕看起來像私密密鑰、API 權杖、卡號或密碼行的項目。",
            statusNoRunner: "沒有模型執行程式回應",
            statusReady: "已就緒，正在使用 %@",
            statusModelNotInstalled: "執行程式已啟動，但「%@」尚未安裝",
            check: "檢查")
        }
    }
}
