// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 AltF4 contributors

import Foundation

struct NotesStrings {
    let title: String
    let newNote: String
    let search: String
    /// Names a note that has no text and was never renamed.
    let untitled: String
    let noAdditionalText: String
    let empty: String
    let pinned: String
    let pin: String
    let unpin: String
    let noResults: String
    let rename: String
    let delete: String
    let deleteTitle: String
    let deleteMessage: String
    let cancel: String
    let format: String
    let styleTitle: String
    let styleHeading: String
    let styleBody: String
    let bold: String
    let italic: String
    let underline: String
    let strikethrough: String
    let bulletedList: String
    let numberedList: String
    let checklist: String
    let yesterday: String
    let unreadable: String
}

extension FeatureStrings {
    static func notes(_ language: AppLanguage) -> NotesStrings {
        switch language {
        case .enUS: return NotesStrings(
            title: "Notes",
            newNote: "New Note",
            search: "Search",
            untitled: "New Note",
            noAdditionalText: "No additional text",
            empty: "No notes yet",
            pinned: "Pinned",
            pin: "Pin Note",
            unpin: "Unpin Note",
            noResults: "No notes match your search.",
            rename: "Rename",
            delete: "Delete",
            deleteTitle: "Delete this note?",
            deleteMessage: "The note and anything pasted into it are removed from this Mac.",
            cancel: "Cancel",
            format: "Format",
            styleTitle: "Title",
            styleHeading: "Heading",
            styleBody: "Body",
            bold: "Bold",
            italic: "Italic",
            underline: "Underline",
            strikethrough: "Strikethrough",
            bulletedList: "Bulleted List",
            numberedList: "Numbered List",
            checklist: "Checklist",
            yesterday: "Yesterday",
            unreadable: "These notes could not be read, so nothing is saved over them.")
        case .ptBR: return NotesStrings(
            title: "Notas",
            newNote: "Nova Nota",
            search: "Buscar",
            untitled: "Nova Nota",
            noAdditionalText: "Nenhum texto adicional",
            empty: "Nenhuma nota ainda",
            pinned: "Fixadas",
            pin: "Fixar Nota",
            unpin: "Desafixar Nota",
            noResults: "Nenhuma nota corresponde à busca.",
            rename: "Renomear",
            delete: "Apagar",
            deleteTitle: "Apagar esta nota?",
            deleteMessage: "A nota e tudo o que foi colado nela são removidos deste Mac.",
            cancel: "Cancelar",
            format: "Formatar",
            styleTitle: "Título",
            styleHeading: "Cabeçalho",
            styleBody: "Corpo",
            bold: "Negrito",
            italic: "Itálico",
            underline: "Sublinhado",
            strikethrough: "Tachado",
            bulletedList: "Lista com Marcadores",
            numberedList: "Lista Numerada",
            checklist: "Lista de Verificação",
            yesterday: "Ontem",
            unreadable: "Não foi possível ler as notas, então nada é salvo por cima delas.")
        case .tr: return NotesStrings(
            title: "Notlar",
            newNote: "Yeni Not",
            search: "Ara",
            untitled: "Yeni Not",
            noAdditionalText: "Ek metin yok",
            empty: "Henüz not yok",
            pinned: "Sabitlenmiş",
            pin: "Notu Sabitle",
            unpin: "Notun Sabitlemesini Kaldır",
            noResults: "Aramayla eşleşen not yok.",
            rename: "Yeniden Adlandır",
            delete: "Sil",
            deleteTitle: "Bu not silinsin mi?",
            deleteMessage: "Not ve içine yapıştırılan her şey bu Mac’ten kaldırılır.",
            cancel: "Vazgeç",
            format: "Biçim",
            styleTitle: "Başlık",
            styleHeading: "Ara Başlık",
            styleBody: "Gövde",
            bold: "Kalın",
            italic: "İtalik",
            underline: "Altı Çizili",
            strikethrough: "Üstü Çizili",
            bulletedList: "Madde İşaretli Liste",
            numberedList: "Numaralı Liste",
            checklist: "Denetim Listesi",
            yesterday: "Dün",
            unreadable: "Notlar okunamadı, bu yüzden üzerlerine hiçbir şey kaydedilmiyor.")
        case .ru: return NotesStrings(
            title: "Заметки",
            newNote: "Новая заметка",
            search: "Поиск",
            untitled: "Новая заметка",
            noAdditionalText: "Нет дополнительного текста",
            empty: "Заметок пока нет",
            pinned: "Закреплено",
            pin: "Закрепить заметку",
            unpin: "Открепить заметку",
            noResults: "Нет заметок, подходящих под поиск.",
            rename: "Переименовать",
            delete: "Удалить",
            deleteTitle: "Удалить эту заметку?",
            deleteMessage: "Заметка и всё, что в неё вставлено, будут удалены с этого Mac.",
            cancel: "Отменить",
            format: "Формат",
            styleTitle: "Название",
            styleHeading: "Заголовок",
            styleBody: "Основной текст",
            bold: "Жирный",
            italic: "Курсив",
            underline: "Подчёркнутый",
            strikethrough: "Зачёркнутый",
            bulletedList: "Маркированный список",
            numberedList: "Нумерованный список",
            checklist: "Список дел",
            yesterday: "Вчера",
            unreadable: "Не удалось прочитать заметки, поэтому поверх них ничего не сохраняется.")
        case .es: return NotesStrings(
            title: "Notas",
            newNote: "Nueva nota",
            search: "Buscar",
            untitled: "Nueva nota",
            noAdditionalText: "Sin texto adicional",
            empty: "Aún no hay notas",
            pinned: "Fijadas",
            pin: "Fijar nota",
            unpin: "Dejar de fijar nota",
            noResults: "Ninguna nota coincide con la búsqueda.",
            rename: "Renombrar",
            delete: "Eliminar",
            deleteTitle: "¿Eliminar esta nota?",
            deleteMessage: "La nota y todo lo que se haya pegado en ella se eliminan de este Mac.",
            cancel: "Cancelar",
            format: "Formato",
            styleTitle: "Título",
            styleHeading: "Encabezado",
            styleBody: "Cuerpo",
            bold: "Negrita",
            italic: "Cursiva",
            underline: "Subrayado",
            strikethrough: "Tachado",
            bulletedList: "Lista con viñetas",
            numberedList: "Lista numerada",
            checklist: "Lista de comprobación",
            yesterday: "Ayer",
            unreadable: "No se han podido leer las notas, así que no se guarda nada encima.")
        case .de: return NotesStrings(
            title: "Notizen",
            newNote: "Neue Notiz",
            search: "Suchen",
            untitled: "Neue Notiz",
            noAdditionalText: "Kein zusätzlicher Text",
            empty: "Noch keine Notizen",
            pinned: "Angepinnt",
            pin: "Notiz anpinnen",
            unpin: "Notiz lösen",
            noResults: "Keine Notiz passt zur Suche.",
            rename: "Umbenennen",
            delete: "Löschen",
            deleteTitle: "Diese Notiz löschen?",
            deleteMessage: "Die Notiz und alles darin Eingefügte werden von diesem Mac entfernt.",
            cancel: "Abbrechen",
            format: "Format",
            styleTitle: "Titel",
            styleHeading: "Überschrift",
            styleBody: "Textkörper",
            bold: "Fett",
            italic: "Kursiv",
            underline: "Unterstrichen",
            strikethrough: "Durchgestrichen",
            bulletedList: "Aufzählung",
            numberedList: "Nummerierte Liste",
            checklist: "Checkliste",
            yesterday: "Gestern",
            unreadable: "Die Notizen konnten nicht gelesen werden, deshalb wird nichts darüber gesichert.")
        case .fr: return NotesStrings(
            title: "Notes",
            newNote: "Nouvelle note",
            search: "Rechercher",
            untitled: "Nouvelle note",
            noAdditionalText: "Aucun texte supplémentaire",
            empty: "Aucune note pour l’instant",
            pinned: "Épinglées",
            pin: "Épingler la note",
            unpin: "Désépingler la note",
            noResults: "Aucune note ne correspond à la recherche.",
            rename: "Renommer",
            delete: "Supprimer",
            deleteTitle: "Supprimer cette note ?",
            deleteMessage: "La note et tout ce qui y a été collé sont supprimés de ce Mac.",
            cancel: "Annuler",
            format: "Format",
            styleTitle: "Titre",
            styleHeading: "En-tête",
            styleBody: "Corps",
            bold: "Gras",
            italic: "Italique",
            underline: "Souligné",
            strikethrough: "Barré",
            bulletedList: "Liste à puces",
            numberedList: "Liste numérotée",
            checklist: "Liste de pointage",
            yesterday: "Hier",
            unreadable: "Impossible de lire les notes : rien n’est enregistré par-dessus.")
        case .it: return NotesStrings(
            title: "Note",
            newNote: "Nuova nota",
            search: "Cerca",
            untitled: "Nuova nota",
            noAdditionalText: "Nessun testo aggiuntivo",
            empty: "Ancora nessuna nota",
            pinned: "Fissate",
            pin: "Fissa nota",
            unpin: "Non fissare più la nota",
            noResults: "Nessuna nota corrisponde alla ricerca.",
            rename: "Rinomina",
            delete: "Elimina",
            deleteTitle: "Eliminare questa nota?",
            deleteMessage: "La nota e tutto ciò che vi è stato incollato vengono rimossi da questo Mac.",
            cancel: "Annulla",
            format: "Formato",
            styleTitle: "Titolo",
            styleHeading: "Intestazione",
            styleBody: "Corpo",
            bold: "Grassetto",
            italic: "Corsivo",
            underline: "Sottolineato",
            strikethrough: "Barrato",
            bulletedList: "Elenco puntato",
            numberedList: "Elenco numerato",
            checklist: "Lista di controllo",
            yesterday: "Ieri",
            unreadable: "Impossibile leggere le note, quindi non viene salvato nulla sopra di esse.")
        case .ja: return NotesStrings(
            title: "メモ",
            newNote: "新規メモ",
            search: "検索",
            untitled: "新規メモ",
            noAdditionalText: "追加テキストなし",
            empty: "まだメモはありません",
            pinned: "ピンで固定",
            pin: "メモをピンで固定",
            unpin: "メモのピンを外す",
            noResults: "検索に一致するメモはありません。",
            rename: "名前を変更",
            delete: "削除",
            deleteTitle: "このメモを削除しますか？",
            deleteMessage: "メモとそこにペーストした内容がこのMacから削除されます。",
            cancel: "キャンセル",
            format: "フォーマット",
            styleTitle: "タイトル",
            styleHeading: "見出し",
            styleBody: "本文",
            bold: "太字",
            italic: "斜体",
            underline: "下線",
            strikethrough: "取り消し線",
            bulletedList: "箇条書き",
            numberedList: "番号付きリスト",
            checklist: "チェックリスト",
            yesterday: "昨日",
            unreadable: "メモを読み込めなかったため、上書き保存はしません。")
        case .ko: return NotesStrings(
            title: "메모",
            newNote: "새로운 메모",
            search: "검색",
            untitled: "새로운 메모",
            noAdditionalText: "추가 텍스트 없음",
            empty: "아직 메모가 없습니다",
            pinned: "고정됨",
            pin: "메모 고정",
            unpin: "메모 고정 해제",
            noResults: "검색과 일치하는 메모가 없습니다.",
            rename: "이름 변경",
            delete: "삭제",
            deleteTitle: "이 메모를 삭제하겠습니까?",
            deleteMessage: "메모와 메모에 붙여넣은 모든 항목이 이 Mac에서 제거됩니다.",
            cancel: "취소",
            format: "포맷",
            styleTitle: "제목",
            styleHeading: "머리말",
            styleBody: "본문",
            bold: "볼드체",
            italic: "이탤릭체",
            underline: "밑줄",
            strikethrough: "취소선",
            bulletedList: "글머리 기호 목록",
            numberedList: "번호 매기기 목록",
            checklist: "체크리스트",
            yesterday: "어제",
            unreadable: "메모를 읽을 수 없어 그 위에 아무것도 저장하지 않습니다.")
        case .zhHans: return NotesStrings(
            title: "备忘录",
            newNote: "新建备忘录",
            search: "搜索",
            untitled: "新建备忘录",
            noAdditionalText: "无附加文本",
            empty: "还没有备忘录",
            pinned: "已置顶",
            pin: "置顶备忘录",
            unpin: "取消置顶备忘录",
            noResults: "没有与搜索匹配的备忘录。",
            rename: "重新命名",
            delete: "删除",
            deleteTitle: "删除此备忘录？",
            deleteMessage: "此备忘录及其中粘贴的所有内容将从这台 Mac 上移除。",
            cancel: "取消",
            format: "格式",
            styleTitle: "标题",
            styleHeading: "小标题",
            styleBody: "正文",
            bold: "粗体",
            italic: "斜体",
            underline: "下划线",
            strikethrough: "删除线",
            bulletedList: "项目符号列表",
            numberedList: "编号列表",
            checklist: "核对清单",
            yesterday: "昨天",
            unreadable: "无法读取备忘录，因此不会覆盖保存。")
        case .zhTW: return NotesStrings(
            title: "備忘錄",
            newNote: "新增備忘錄",
            search: "搜尋",
            untitled: "新增備忘錄",
            noAdditionalText: "無其他文字",
            empty: "尚無備忘錄",
            pinned: "已釘選",
            pin: "釘選備忘錄",
            unpin: "取消釘選備忘錄",
            noResults: "沒有符合搜尋的備忘錄。",
            rename: "重新命名",
            delete: "刪除",
            deleteTitle: "要刪除此備忘錄嗎？",
            deleteMessage: "此備忘錄及其中貼上的所有內容將從這台 Mac 移除。",
            cancel: "取消",
            format: "格式",
            styleTitle: "標題",
            styleHeading: "小標題",
            styleBody: "內文",
            bold: "粗體",
            italic: "斜體",
            underline: "底線",
            strikethrough: "刪除線",
            bulletedList: "項目符號列表",
            numberedList: "編號列表",
            checklist: "檢查表",
            yesterday: "昨天",
            unreadable: "無法讀取備忘錄，因此不會覆寫儲存。")
        case .zhHK: return NotesStrings(
            title: "備忘錄",
            newNote: "新增備忘錄",
            search: "搜尋",
            untitled: "新增備忘錄",
            noAdditionalText: "沒有其他文字",
            empty: "尚未有備忘錄",
            pinned: "已釘選",
            pin: "釘選備忘錄",
            unpin: "取消釘選備忘錄",
            noResults: "沒有符合搜尋的備忘錄。",
            rename: "重新命名",
            delete: "刪除",
            deleteTitle: "要刪除這份備忘錄嗎？",
            deleteMessage: "這份備忘錄及當中貼上的所有內容將從這部 Mac 移除。",
            cancel: "取消",
            format: "格式",
            styleTitle: "標題",
            styleHeading: "小標題",
            styleBody: "內文",
            bold: "粗體",
            italic: "斜體",
            underline: "底線",
            strikethrough: "刪除線",
            bulletedList: "項目符號列表",
            numberedList: "編號列表",
            checklist: "檢查表",
            yesterday: "昨天",
            unreadable: "無法讀取備忘錄，因此不會覆寫儲存。")
        }
    }
}
