// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 AltF4 contributors

import Foundation

/// The first run inside the notch: what F4 is, how it opens, which tools
/// to install and the grants they need.
struct OnboardingStrings {
    let slogan: String
    let continueTitle: String
    let back: String
    let language: String
    /// `%@` is the app name.
    let howTitleFormat: String
    let openTitle: String
    let openBody: String
    let homeTitle: String
    let homeBody: String
    let dictateTitle: String
    let dictateBody: String
    let toolsTitle: String
    let toolsBody: String
    let alwaysIncluded: String
    let systemTitle: String
    let systemDetail: String
    let keepAwakeTitle: String
    let keepAwakeDetail: String
    let mixerTitle: String
    let mixerDetail: String
    let capturesTitle: String
    let capturesDetail: String
    let calendarTitle: String
    let calendarDetail: String
    let timerTitle: String
    let timerDetail: String
    let commandBarTitle: String
    let commandBarDetail: String
    let windowsTitle: String
    let windowsDetail: String
    let filesTitle: String
    let filesDetail: String
    let downloadsTitle: String
    let downloadsDetail: String
    let launcherTitle: String
    let launcherDetail: String
    let accessTitle: String
    let accessBody: String
    let reasonAccessibility: String
    let reasonScreenRecording: String
    let reasonMicrophone: String
    let allow: String
    let allowed: String
    let openSettings: String
    let finish: String
}

extension FeatureStrings {
    static func onboarding(_ language: AppLanguage) -> OnboardingStrings {
        switch language {
        case .enUS: return OnboardingStrings(
            slogan: "Everything you need, right in the notch.",
            continueTitle: "Continue",
            back: "Back",
            language: "Language",
            howTitleFormat: "How %@ works",
            openTitle: "Point at the notch",
            openBody: "Move the pointer to the top of the screen and it opens. Move away and it closes.",
            homeTitle: "Start from Home",
            homeBody: "Every tool you install is there, one click away.",
            dictateTitle: "Hold Fn and talk",
            dictateBody: "Let go and the text appears wherever you are typing.",
            toolsTitle: "Choose your tools",
            toolsBody: "Only what you install runs. Install or remove anything you like, whenever you like, in Settings.",
            alwaysIncluded: "Always included",
            systemTitle: "System",
            systemDetail: "CPU, memory and battery",
            keepAwakeTitle: "Keep awake",
            keepAwakeDetail: "Stops your Mac from sleeping",
            mixerTitle: "Volume mixer",
            mixerDetail: "A volume for each app",
            capturesTitle: "Screenshots",
            capturesDetail: "Capture, record and copy text",
            calendarTitle: "Calendar",
            calendarDetail: "Your next events",
            timerTitle: "Timer",
            timerDetail: "Timer, pomodoro and stopwatch",
            commandBarTitle: "Command bar",
            commandBarDetail: "Find anything with ⌥Space",
            windowsTitle: "Windows",
            windowsDetail: "Snap windows into place",
            filesTitle: "File shelf",
            filesDetail: "Keep files at hand in the notch",
            downloadsTitle: "Downloads",
            downloadsDetail: "Follow your downloads",
            launcherTitle: "Utilities",
            launcherDetail: "Handy tools in one place",
            accessTitle: "One last step",
            accessBody: "macOS will ask you to allow a few things. You can also do it later in Settings.",
            reasonAccessibility: "To type your dictation and paste for you.",
            reasonScreenRecording: "For screenshots and recordings.",
            reasonMicrophone: "To hear you when you dictate.",
            allow: "Allow",
            allowed: "Allowed",
            openSettings: "Open Settings",
            finish: "Start")
        case .ptBR: return OnboardingStrings(
            slogan: "Tudo o que você precisa, no notch.",
            continueTitle: "Continuar",
            back: "Voltar",
            language: "Idioma",
            howTitleFormat: "Como o %@ funciona",
            openTitle: "Aponte para o notch",
            openBody: "Leve o ponteiro até o topo da tela e ele abre. Afaste e ele fecha.",
            homeTitle: "Tudo começa no Início",
            homeBody: "As ferramentas que você instalar ficam ali, a um clique.",
            dictateTitle: "Segure Fn e fale",
            dictateBody: "Solte e o texto aparece onde você estiver digitando.",
            toolsTitle: "Escolha suas ferramentas",
            toolsBody: "Só funciona o que você instala. Instale ou remova o que quiser, quando quiser, nos Ajustes.",
            alwaysIncluded: "Sempre incluído",
            systemTitle: "Sistema",
            systemDetail: "CPU, memória e bateria",
            keepAwakeTitle: "Sem repouso",
            keepAwakeDetail: "Impede o Mac de dormir",
            mixerTitle: "Mixer",
            mixerDetail: "Um volume para cada app",
            capturesTitle: "Capturas",
            capturesDetail: "Capture, grave e copie texto",
            calendarTitle: "Calendário",
            calendarDetail: "Seus próximos eventos",
            timerTitle: "Timer",
            timerDetail: "Timer, pomodoro e cronômetro",
            commandBarTitle: "Barra de comandos",
            commandBarDetail: "Encontre qualquer coisa com ⌥Espaço",
            windowsTitle: "Janelas",
            windowsDetail: "Encaixe as janelas no lugar",
            filesTitle: "Bandeja",
            filesDetail: "Arquivos à mão no notch",
            downloadsTitle: "Downloads",
            downloadsDetail: "Acompanhe seus downloads",
            launcherTitle: "Utilitários",
            launcherDetail: "Ferramentas úteis num só lugar",
            accessTitle: "Um último passo",
            accessBody: "O macOS vai pedir permissão para algumas coisas. Você também pode fazer isso depois nos Ajustes.",
            reasonAccessibility: "Para digitar seu ditado e colar por você.",
            reasonScreenRecording: "Para capturas e gravações.",
            reasonMicrophone: "Para ouvir você quando dita.",
            allow: "Permitir",
            allowed: "Permitido",
            openSettings: "Abrir Ajustes",
            finish: "Começar")
        case .tr: return OnboardingStrings(
            slogan: "İhtiyacın olan her şey çentikte.",
            continueTitle: "Devam",
            back: "Geri",
            language: "Dil",
            howTitleFormat: "%@ nasıl çalışır",
            openTitle: "Çentiği işaret et",
            openBody: "İmleci ekranın en üstüne götür, açılır. Uzaklaştır, kapanır.",
            homeTitle: "Her şey Ana Sayfa’da başlar",
            homeBody: "Kurduğun araçlar orada, bir tık uzağında.",
            dictateTitle: "Fn’ye basılı tut ve konuş",
            dictateBody: "Bırak, metin yazdığın yerde belirsin.",
            toolsTitle: "Araçlarını seç",
            toolsBody: "Yalnızca kurduğun şeyler çalışır. İstediğini, istediğin zaman Ayarlar’dan kur ya da kaldır.",
            alwaysIncluded: "Her zaman dahil",
            systemTitle: "Sistem",
            systemDetail: "CPU, bellek ve pil",
            keepAwakeTitle: "Uyanık tut",
            keepAwakeDetail: "Mac’in uyumasını engeller",
            mixerTitle: "Mikser",
            mixerDetail: "Her uygulamaya ayrı ses",
            capturesTitle: "Ekran görüntüleri",
            capturesDetail: "Yakala, kaydet, metni kopyala",
            calendarTitle: "Takvim",
            calendarDetail: "Yaklaşan etkinliklerin",
            timerTitle: "Zamanlayıcı",
            timerDetail: "Zamanlayıcı, pomodoro ve kronometre",
            commandBarTitle: "Komut çubuğu",
            commandBarDetail: "⌥Boşluk ile her şeyi bul",
            windowsTitle: "Pencereler",
            windowsDetail: "Pencereleri hızla yerleştir",
            filesTitle: "Raf",
            filesDetail: "Dosyalar çentikte, elinin altında",
            downloadsTitle: "İndirmeler",
            downloadsDetail: "İndirmelerini takip et",
            launcherTitle: "Araç kutusu",
            launcherDetail: "Kullanışlı araçlar tek yerde",
            accessTitle: "Son bir adım",
            accessBody: "macOS birkaç izin isteyecek. Bunu daha sonra Ayarlar’dan da yapabilirsin.",
            reasonAccessibility: "Dikteni yazmak ve senin yerine yapıştırmak için.",
            reasonScreenRecording: "Ekran görüntüleri ve kayıtlar için.",
            reasonMicrophone: "Dikte ederken seni duymak için.",
            allow: "İzin ver",
            allowed: "İzin verildi",
            openSettings: "Ayarlar’ı aç",
            finish: "Başla")
        case .ru: return OnboardingStrings(
            slogan: "Всё, что нужно, прямо в вырезе.",
            continueTitle: "Продолжить",
            back: "Назад",
            language: "Язык",
            howTitleFormat: "Как работает %@",
            openTitle: "Наведите на вырез",
            openBody: "Подведите указатель к самому верху экрана, и панель откроется. Уведите его, и она закроется.",
            homeTitle: "Всё начинается с главной",
            homeBody: "Здесь все установленные инструменты, в один клик.",
            dictateTitle: "Удерживайте Fn и говорите",
            dictateBody: "Отпустите, и текст появится там, где вы печатаете.",
            toolsTitle: "Выберите инструменты",
            toolsBody: "Работает только то, что вы установили. Устанавливайте и удаляйте что угодно и когда угодно в Настройках.",
            alwaysIncluded: "Всегда включено",
            systemTitle: "Система",
            systemDetail: "Процессор, память и батарея",
            keepAwakeTitle: "Без сна",
            keepAwakeDetail: "Не даёт Mac уснуть",
            mixerTitle: "Микшер",
            mixerDetail: "Своя громкость для каждого приложения",
            capturesTitle: "Снимки экрана",
            capturesDetail: "Снимайте, записывайте, копируйте текст",
            calendarTitle: "Календарь",
            calendarDetail: "Ближайшие события",
            timerTitle: "Таймер",
            timerDetail: "Таймер, помидоро и секундомер",
            commandBarTitle: "Командная строка",
            commandBarDetail: "Находите всё через ⌥Пробел",
            windowsTitle: "Окна",
            windowsDetail: "Быстро расставляйте окна",
            filesTitle: "Полка",
            filesDetail: "Файлы под рукой, прямо в вырезе",
            downloadsTitle: "Загрузки",
            downloadsDetail: "Следите за загрузками",
            launcherTitle: "Утилиты",
            launcherDetail: "Полезные инструменты в одном месте",
            accessTitle: "Последний шаг",
            accessBody: "macOS попросит несколько разрешений. Это можно сделать и позже в Настройках.",
            reasonAccessibility: "Чтобы печатать диктовку и вставлять текст за вас.",
            reasonScreenRecording: "Для снимков и записи экрана.",
            reasonMicrophone: "Чтобы слышать вас при диктовке.",
            allow: "Разрешить",
            allowed: "Разрешено",
            openSettings: "Открыть Настройки",
            finish: "Начать")
        case .es: return OnboardingStrings(
            slogan: "Todo lo que necesitas, en el notch.",
            continueTitle: "Continuar",
            back: "Atrás",
            language: "Idioma",
            howTitleFormat: "Así funciona %@",
            openTitle: "Apunta al notch",
            openBody: "Lleva el puntero arriba del todo y se abre. Apártalo y se cierra.",
            homeTitle: "Todo empieza en Inicio",
            homeBody: "Ahí están las herramientas que instales, a un clic.",
            dictateTitle: "Mantén Fn y habla",
            dictateBody: "Suelta y el texto aparece donde estés escribiendo.",
            toolsTitle: "Elige tus herramientas",
            toolsBody: "Solo funciona lo que instalas. Instala o quita lo que quieras, cuando quieras, en Ajustes.",
            alwaysIncluded: "Siempre incluido",
            systemTitle: "Sistema",
            systemDetail: "CPU, memoria y batería",
            keepAwakeTitle: "Sin reposo",
            keepAwakeDetail: "Evita que el Mac se duerma",
            mixerTitle: "Mezclador",
            mixerDetail: "Un volumen para cada app",
            capturesTitle: "Capturas",
            capturesDetail: "Captura, graba y copia texto",
            calendarTitle: "Calendario",
            calendarDetail: "Tus próximos eventos",
            timerTitle: "Temporizador",
            timerDetail: "Temporizador, pomodoro y cronómetro",
            commandBarTitle: "Barra de comandos",
            commandBarDetail: "Encuentra lo que sea con ⌥Espacio",
            windowsTitle: "Ventanas",
            windowsDetail: "Coloca las ventanas en su sitio",
            filesTitle: "Bandeja",
            filesDetail: "Tus archivos a mano en el notch",
            downloadsTitle: "Descargas",
            downloadsDetail: "Sigue tus descargas",
            launcherTitle: "Utilidades",
            launcherDetail: "Herramientas prácticas en un solo sitio",
            accessTitle: "Un último paso",
            accessBody: "macOS te pedirá permiso para algunas cosas. También puedes hacerlo luego en Ajustes.",
            reasonAccessibility: "Para escribir tu dictado y pegar por ti.",
            reasonScreenRecording: "Para capturas y grabaciones.",
            reasonMicrophone: "Para oírte cuando dictas.",
            allow: "Permitir",
            allowed: "Permitido",
            openSettings: "Abrir Ajustes",
            finish: "Empezar")
        case .de: return OnboardingStrings(
            slogan: "Alles, was du brauchst, in der Notch.",
            continueTitle: "Weiter",
            back: "Zurück",
            language: "Sprache",
            howTitleFormat: "So funktioniert %@",
            openTitle: "Zeig auf die Notch",
            openBody: "Bewege den Zeiger ganz nach oben und sie öffnet sich. Zieh ihn weg und sie schließt sich.",
            homeTitle: "Alles beginnt bei Start",
            homeBody: "Jedes Werkzeug, das du installierst, ist dort nur einen Klick entfernt.",
            dictateTitle: "Halte Fn gedrückt und sprich",
            dictateBody: "Lass los und der Text erscheint dort, wo du gerade schreibst.",
            toolsTitle: "Wähle deine Werkzeuge",
            toolsBody: "Es läuft nur, was du installierst. Installiere oder entferne jederzeit, was du willst, in den Einstellungen.",
            alwaysIncluded: "Immer dabei",
            systemTitle: "System",
            systemDetail: "CPU, Speicher und Batterie",
            keepAwakeTitle: "Wach halten",
            keepAwakeDetail: "Verhindert, dass der Mac schläft",
            mixerTitle: "Mixer",
            mixerDetail: "Eine Lautstärke pro App",
            capturesTitle: "Bildschirmfotos",
            capturesDetail: "Aufnehmen, filmen, Text kopieren",
            calendarTitle: "Kalender",
            calendarDetail: "Deine nächsten Termine",
            timerTitle: "Timer",
            timerDetail: "Timer, Pomodoro und Stoppuhr",
            commandBarTitle: "Befehlsleiste",
            commandBarDetail: "Finde alles mit ⌥Leertaste",
            windowsTitle: "Fenster",
            windowsDetail: "Fenster schnell anordnen",
            filesTitle: "Ablage",
            filesDetail: "Dateien griffbereit in der Notch",
            downloadsTitle: "Downloads",
            downloadsDetail: "Behalte deine Downloads im Blick",
            launcherTitle: "Hilfsprogramme",
            launcherDetail: "Praktische Helfer an einem Ort",
            accessTitle: "Ein letzter Schritt",
            accessBody: "macOS fragt dich nach ein paar Erlaubnissen. Du kannst das auch später in den Einstellungen tun.",
            reasonAccessibility: "Um dein Diktat zu tippen und für dich einzufügen.",
            reasonScreenRecording: "Für Bildschirmfotos und Aufnahmen.",
            reasonMicrophone: "Um dich beim Diktieren zu hören.",
            allow: "Erlauben",
            allowed: "Erlaubt",
            openSettings: "Einstellungen öffnen",
            finish: "Los geht’s")
        case .fr: return OnboardingStrings(
            slogan: "Tout ce qu’il vous faut, dans l’encoche.",
            continueTitle: "Continuer",
            back: "Retour",
            language: "Langue",
            howTitleFormat: "Comment fonctionne %@",
            openTitle: "Visez l’encoche",
            openBody: "Placez le pointeur tout en haut de l’écran et elle s’ouvre. Éloignez-le et elle se ferme.",
            homeTitle: "Tout part de l’Accueil",
            homeBody: "Les outils que vous installez y sont, à un clic.",
            dictateTitle: "Maintenez Fn et parlez",
            dictateBody: "Relâchez et le texte s’écrit là où vous tapez.",
            toolsTitle: "Choisissez vos outils",
            toolsBody: "Seul ce que vous installez fonctionne. Installez ou retirez ce que vous voulez, quand vous voulez, dans les Réglages.",
            alwaysIncluded: "Toujours inclus",
            systemTitle: "Système",
            systemDetail: "Processeur, mémoire et batterie",
            keepAwakeTitle: "Anti-veille",
            keepAwakeDetail: "Empêche le Mac de se mettre en veille",
            mixerTitle: "Mixeur",
            mixerDetail: "Un volume pour chaque app",
            capturesTitle: "Captures",
            capturesDetail: "Capturez, enregistrez, copiez du texte",
            calendarTitle: "Calendrier",
            calendarDetail: "Vos prochains événements",
            timerTitle: "Minuteur",
            timerDetail: "Minuteur, pomodoro et chrono",
            commandBarTitle: "Barre de commandes",
            commandBarDetail: "Trouvez tout avec ⌥Espace",
            windowsTitle: "Fenêtres",
            windowsDetail: "Rangez les fenêtres en un geste",
            filesTitle: "Étagère",
            filesDetail: "Vos fichiers à portée, dans l’encoche",
            downloadsTitle: "Téléchargements",
            downloadsDetail: "Suivez vos téléchargements",
            launcherTitle: "Utilitaires",
            launcherDetail: "Des outils pratiques au même endroit",
            accessTitle: "Une dernière étape",
            accessBody: "macOS vous demandera d’autoriser quelques accès. Vous pouvez aussi le faire plus tard dans les Réglages.",
            reasonAccessibility: "Pour écrire votre dictée et coller à votre place.",
            reasonScreenRecording: "Pour les captures et les enregistrements.",
            reasonMicrophone: "Pour vous entendre quand vous dictez.",
            allow: "Autoriser",
            allowed: "Autorisé",
            openSettings: "Ouvrir les Réglages",
            finish: "Commencer")
        case .it: return OnboardingStrings(
            slogan: "Tutto ciò che ti serve, nel notch.",
            continueTitle: "Continua",
            back: "Indietro",
            language: "Lingua",
            howTitleFormat: "Come funziona %@",
            openTitle: "Punta al notch",
            openBody: "Porta il puntatore in cima allo schermo e si apre. Allontanalo e si chiude.",
            homeTitle: "Tutto parte dalla Home",
            homeBody: "Gli strumenti che installi sono lì, a un clic.",
            dictateTitle: "Tieni premuto Fn e parla",
            dictateBody: "Rilascia e il testo compare dove stai scrivendo.",
            toolsTitle: "Scegli i tuoi strumenti",
            toolsBody: "Funziona solo ciò che installi. Installa o rimuovi quello che vuoi, quando vuoi, nelle Impostazioni.",
            alwaysIncluded: "Sempre inclusi",
            systemTitle: "Sistema",
            systemDetail: "CPU, memoria e batteria",
            keepAwakeTitle: "Sempre sveglio",
            keepAwakeDetail: "Impedisce al Mac di andare in stop",
            mixerTitle: "Mixer",
            mixerDetail: "Un volume per ogni app",
            capturesTitle: "Istantanee",
            capturesDetail: "Cattura, registra e copia testo",
            calendarTitle: "Calendario",
            calendarDetail: "I tuoi prossimi eventi",
            timerTitle: "Timer",
            timerDetail: "Timer, pomodoro e cronometro",
            commandBarTitle: "Barra dei comandi",
            commandBarDetail: "Trova tutto con ⌥Spazio",
            windowsTitle: "Finestre",
            windowsDetail: "Sistema le finestre al volo",
            filesTitle: "Ripiano",
            filesDetail: "File a portata di mano nel notch",
            downloadsTitle: "Download",
            downloadsDetail: "Segui i tuoi download",
            launcherTitle: "Utility",
            launcherDetail: "Strumenti utili in un solo posto",
            accessTitle: "Un ultimo passo",
            accessBody: "macOS ti chiederà alcuni permessi. Puoi farlo anche dopo nelle Impostazioni.",
            reasonAccessibility: "Per scrivere la tua dettatura e incollare al posto tuo.",
            reasonScreenRecording: "Per istantanee e registrazioni.",
            reasonMicrophone: "Per sentirti quando detti.",
            allow: "Consenti",
            allowed: "Consentito",
            openSettings: "Apri Impostazioni",
            finish: "Inizia")
        case .ja: return OnboardingStrings(
            slogan: "必要なものは、すべてノッチに。",
            continueTitle: "続ける",
            back: "戻る",
            language: "言語",
            howTitleFormat: "%@ の使い方",
            openTitle: "ノッチにポインタを合わせる",
            openBody: "ポインタを画面のいちばん上へ動かすと開き、離すと閉じます。",
            homeTitle: "すべてはホームから",
            homeBody: "インストールしたツールがワンクリックで使えます。",
            dictateTitle: "Fn を押したまま話す",
            dictateBody: "指を離すと、入力中の場所にテキストが入ります。",
            toolsTitle: "ツールを選ぶ",
            toolsBody: "動くのはインストールしたものだけです。いつでも設定から自由にインストールや削除ができます。",
            alwaysIncluded: "常に含まれるもの",
            systemTitle: "システム",
            systemDetail: "CPU、メモリ、バッテリー",
            keepAwakeTitle: "スリープ防止",
            keepAwakeDetail: "Mac をスリープさせません",
            mixerTitle: "ミキサー",
            mixerDetail: "アプリごとの音量",
            capturesTitle: "スクリーンショット",
            capturesDetail: "撮影、録画、テキストのコピー",
            calendarTitle: "カレンダー",
            calendarDetail: "次の予定",
            timerTitle: "タイマー",
            timerDetail: "タイマー、ポモドーロ、ストップウォッチ",
            commandBarTitle: "コマンドバー",
            commandBarDetail: "⌥Space で何でも検索",
            windowsTitle: "ウインドウ",
            windowsDetail: "ウインドウをすばやく整列",
            filesTitle: "シェルフ",
            filesDetail: "ファイルをノッチに置いておける",
            downloadsTitle: "ダウンロード",
            downloadsDetail: "ダウンロードの進み具合",
            launcherTitle: "ユーティリティ",
            launcherDetail: "便利なツールをひとまとめに",
            accessTitle: "最後のステップ",
            accessBody: "macOS がいくつか許可を求めます。あとで設定から行うこともできます。",
            reasonAccessibility: "音声入力の文字を打ち込み、代わりにペーストするため。",
            reasonScreenRecording: "スクリーンショットと録画のため。",
            reasonMicrophone: "音声入力であなたの声を聞くため。",
            allow: "許可",
            allowed: "許可済み",
            openSettings: "設定を開く",
            finish: "はじめる")
        case .ko: return OnboardingStrings(
            slogan: "필요한 모든 것을 노치에.",
            continueTitle: "계속",
            back: "뒤로",
            language: "언어",
            howTitleFormat: "%@ 사용법",
            openTitle: "노치를 가리키세요",
            openBody: "포인터를 화면 맨 위로 옮기면 열리고, 벗어나면 닫힙니다.",
            homeTitle: "모든 건 홈에서 시작",
            homeBody: "설치한 도구가 모두 클릭 한 번 거리에 있습니다.",
            dictateTitle: "Fn을 누른 채 말하세요",
            dictateBody: "손을 떼면 입력 중인 곳에 텍스트가 들어갑니다.",
            toolsTitle: "도구를 고르세요",
            toolsBody: "설치한 것만 작동합니다. 언제든 설정에서 원하는 것을 설치하거나 제거할 수 있습니다.",
            alwaysIncluded: "항상 포함",
            systemTitle: "시스템",
            systemDetail: "CPU, 메모리, 배터리",
            keepAwakeTitle: "잠자기 방지",
            keepAwakeDetail: "Mac이 잠들지 않게 합니다",
            mixerTitle: "믹서",
            mixerDetail: "앱마다 따로 음량 조절",
            capturesTitle: "스크린샷",
            capturesDetail: "캡처, 녹화, 텍스트 복사",
            calendarTitle: "캘린더",
            calendarDetail: "다가오는 일정",
            timerTitle: "타이머",
            timerDetail: "타이머, 뽀모도로, 스톱워치",
            commandBarTitle: "명령 막대",
            commandBarDetail: "⌥Space로 무엇이든 찾기",
            windowsTitle: "윈도우",
            windowsDetail: "윈도우를 빠르게 배치",
            filesTitle: "보관함",
            filesDetail: "파일을 노치에 두고 바로 사용",
            downloadsTitle: "다운로드",
            downloadsDetail: "다운로드 진행 상황 보기",
            launcherTitle: "유틸리티",
            launcherDetail: "유용한 도구를 한곳에",
            accessTitle: "마지막 단계",
            accessBody: "macOS가 몇 가지 권한을 요청합니다. 나중에 설정에서 해도 됩니다.",
            reasonAccessibility: "받아쓴 내용을 입력하고 대신 붙여 넣기 위해.",
            reasonScreenRecording: "스크린샷과 화면 녹화를 위해.",
            reasonMicrophone: "받아쓰기할 때 목소리를 듣기 위해.",
            allow: "허용",
            allowed: "허용됨",
            openSettings: "설정 열기",
            finish: "시작하기")
        case .zhHans: return OnboardingStrings(
            slogan: "你需要的一切，都在刘海里。",
            continueTitle: "继续",
            back: "返回",
            language: "语言",
            howTitleFormat: "%@ 的用法",
            openTitle: "指向刘海",
            openBody: "把指针移到屏幕最上方即可打开，移开就会关闭。",
            homeTitle: "一切从主页开始",
            homeBody: "你安装的工具都在这里，一键即达。",
            dictateTitle: "按住 Fn 说话",
            dictateBody: "松开后，文字会出现在你正在输入的地方。",
            toolsTitle: "选择你的工具",
            toolsBody: "只有你安装的功能才会运行。随时可以在设置中安装或移除任何工具。",
            alwaysIncluded: "始终包含",
            systemTitle: "系统",
            systemDetail: "CPU、内存和电池",
            keepAwakeTitle: "防止睡眠",
            keepAwakeDetail: "让 Mac 保持唤醒",
            mixerTitle: "混音器",
            mixerDetail: "每个 App 单独调音量",
            capturesTitle: "截屏",
            capturesDetail: "截图、录屏、复制文字",
            calendarTitle: "日历",
            calendarDetail: "接下来的日程",
            timerTitle: "计时器",
            timerDetail: "计时器、番茄钟和秒表",
            commandBarTitle: "命令栏",
            commandBarDetail: "用 ⌥空格 查找一切",
            windowsTitle: "窗口",
            windowsDetail: "快速摆放窗口",
            filesTitle: "文件架",
            filesDetail: "把文件放在刘海里随手取用",
            downloadsTitle: "下载",
            downloadsDetail: "查看下载进度",
            launcherTitle: "实用工具",
            launcherDetail: "常用工具集中在一处",
            accessTitle: "最后一步",
            accessBody: "macOS 会请求几项权限。你也可以稍后在设置中完成。",
            reasonAccessibility: "用于输入听写内容并替你粘贴。",
            reasonScreenRecording: "用于截屏和录屏。",
            reasonMicrophone: "用于在听写时听到你的声音。",
            allow: "允许",
            allowed: "已允许",
            openSettings: "打开设置",
            finish: "开始使用")
        case .zhTW: return OnboardingStrings(
            slogan: "你需要的一切，都在瀏海裡。",
            continueTitle: "繼續",
            back: "返回",
            language: "語言",
            howTitleFormat: "%@ 的用法",
            openTitle: "指向瀏海",
            openBody: "將指標移到螢幕最上方即可開啟，移開就會關閉。",
            homeTitle: "一切從首頁開始",
            homeBody: "你安裝的工具都在這裡，一鍵即達。",
            dictateTitle: "按住 Fn 說話",
            dictateBody: "放開後，文字會出現在你正在輸入的地方。",
            toolsTitle: "選擇你的工具",
            toolsBody: "只有你安裝的功能才會執行。隨時可以在設定中安裝或移除任何工具。",
            alwaysIncluded: "永遠包含",
            systemTitle: "系統",
            systemDetail: "CPU、記憶體和電池",
            keepAwakeTitle: "防止睡眠",
            keepAwakeDetail: "讓 Mac 保持喚醒",
            mixerTitle: "混音器",
            mixerDetail: "每個 App 各自調整音量",
            capturesTitle: "截圖",
            capturesDetail: "截圖、錄影、複製文字",
            calendarTitle: "行事曆",
            calendarDetail: "接下來的行程",
            timerTitle: "計時器",
            timerDetail: "計時器、番茄鐘和碼錶",
            commandBarTitle: "指令列",
            commandBarDetail: "用 ⌥空白鍵 找到一切",
            windowsTitle: "視窗",
            windowsDetail: "快速擺放視窗",
            filesTitle: "檔案架",
            filesDetail: "把檔案放在瀏海裡隨手取用",
            downloadsTitle: "下載",
            downloadsDetail: "查看下載進度",
            launcherTitle: "工具程式",
            launcherDetail: "常用工具集中在一處",
            accessTitle: "最後一步",
            accessBody: "macOS 會要求幾項權限。你也可以稍後在設定中完成。",
            reasonAccessibility: "用於輸入聽寫內容並替你貼上。",
            reasonScreenRecording: "用於截圖和螢幕錄影。",
            reasonMicrophone: "用於在聽寫時聽到你的聲音。",
            allow: "允許",
            allowed: "已允許",
            openSettings: "打開設定",
            finish: "開始使用")
        case .zhHK: return OnboardingStrings(
            slogan: "你需要嘅一切，都喺瀏海度。",
            continueTitle: "繼續",
            back: "返回",
            language: "語言",
            howTitleFormat: "%@ 點樣用",
            openTitle: "指向瀏海",
            openBody: "將指標移到螢幕最頂就會打開，移開就會關閉。",
            homeTitle: "一切由主頁開始",
            homeBody: "你安裝嘅工具都喺度，一撳即達。",
            dictateTitle: "撳住 Fn 講嘢",
            dictateBody: "放開之後，文字會出現喺你輸入緊嘅位置。",
            toolsTitle: "揀你嘅工具",
            toolsBody: "只有你安裝嘅功能先會運行。隨時可以喺設定度安裝或者移除任何工具。",
            alwaysIncluded: "一定包括",
            systemTitle: "系統",
            systemDetail: "CPU、記憶體同電池",
            keepAwakeTitle: "防止睡眠",
            keepAwakeDetail: "等 Mac 保持喚醒",
            mixerTitle: "混音器",
            mixerDetail: "每個 App 各自調音量",
            capturesTitle: "截圖",
            capturesDetail: "截圖、錄影、複製文字",
            calendarTitle: "日曆",
            calendarDetail: "接落嚟嘅行程",
            timerTitle: "計時器",
            timerDetail: "計時器、番茄鐘同秒錶",
            commandBarTitle: "指令列",
            commandBarDetail: "用 ⌥空白鍵 搵到一切",
            windowsTitle: "視窗",
            windowsDetail: "快速擺放視窗",
            filesTitle: "檔案架",
            filesDetail: "將檔案放喺瀏海度隨手攞",
            downloadsTitle: "下載",
            downloadsDetail: "睇下載進度",
            launcherTitle: "工具程式",
            launcherDetail: "常用工具集中喺一處",
            accessTitle: "最後一步",
            accessBody: "macOS 會要求幾項權限。你都可以遲啲喺設定度完成。",
            reasonAccessibility: "用嚟輸入聽寫內容同幫你貼上。",
            reasonScreenRecording: "用嚟截圖同錄影。",
            reasonMicrophone: "用嚟喺聽寫時聽到你把聲。",
            allow: "允許",
            allowed: "已允許",
            openSettings: "打開設定",
            finish: "開始使用")
        }
    }
}
